# 工业互联网术语和定义

新增加条目格式：

- 软件定义网络（Software Defined Network, 缩略语:SDN） :: 一种网络控制和转发分离的网络架构，上层应用和服务可通过网络控制层的可编程接口实现对底层网络设备的控制。

* 总体组

- 工业互联网（Industrial Internet, II） :: 工业互联网是满足工业智能化发展需求，具有低时延、高可靠、广覆盖特点的关键网络基础设施，是新一代信息通信技术与先进制造业深度融合所形成的新兴业态与应用模式。

- 工业互联网标识解析 :: 工业互联网标识通过赋予每一个产品、零部件、机器设备唯一的“身份证”，实现全网资源的灵活区分和信息管理。工业互联网标识解析类似于互联网域名解析，可以通过产品标识查询储存产品信息的服务器地址，或者查询产品信息以及相关服务。

- 工业互联网平台 :: 指面向制造业数字化、网络化、智能化需求，构建基于海量数据采集、汇聚、分析的服务体系，支撑制造资源泛在连接、弹性供给、高效配置的工业云平台。

- 可编程逻辑控制器（Programmable Logic Controller， 缩略语：PLC） :: 专为工业生产设计的一种数字运算操作的电子装置，它采用一类可编程的存储器，用于其内部存储程序，执行逻辑运算，顺序控制，定时，计数与算术操作等面向用户的指令，并通过数字或模拟式输入/输出控制各种类型的机械或生产过程。是工业控制的核心部分。

-	知识模型	（Knowledge Model） :: 主要解决知识的表示、组织与交互关系，知识的有序化以及知识处理 模型，是将知识进行形式化和结构化的抽象。知识模型不是知识，是知识的抽象，以便于计算机理解与处理。

-	知识模型	（Knowledge Model） :: 主要解决知识的表示、组织与交互关系，知识的有序化以及知识处理 模型，是将知识进行形式化和结构化的抽象。知识模型不是知识，是知识的抽象，以便于计算机理解与处理。

-	智能资产 （Smart Asset） ::	通过融合网络、计算、存储等 ICT 能力，具有自主化和协作化能力的资产（物）。

-	智能网关 （Smart Gateway） ::	通过网络联接、协议转换等功能联接物理和数字世界，提供轻量化的联接管理、实时数据分析及应用管理功能的网关。

-	智能系统 （Smart System） :: 基于多个分布式智能网关、服务器的协同构成智能系统，提供弹性扩展的网络、计算、存储能力。

-	智能服务 （Smart Service） :: 基于模型驱动的统一服务框架，面向系统运维人员、业务决策者、系统集成商、应用开发人员等多种角色，提供开发服务框架和部署 运营服务框架。

-	工业大数据 （Big Industrial Data） :: 工业大数据即工业数据的总和，我们把它分成三类，即企业信息化数据、工业物联网数据，以及外部跨界数据。其中，企业信息化和工业物联网中机器产生的海量时序数据是工业数据规模变大的主要来源。

-	行业智能 1.0（Industry Intelligence 1.0） :: 行业智能 1.0 是面向市场线索、营销、采购、物流、售后等商业过程，将用户、应用和商业流程的行为和 状态数字化，基于多维度数据分析和场景感知，建立行业的信息图谱，为行业用户提供个性化的资源配置和服务。

-	行业智能 2.0	（Industry Intelligence 2.0） ::	行业智能 2.0 面向产品规划、设计、制造、运营等生产过程，产品、生产装备、工艺流程等已经逐步数字化和网络化，行业智能 2.0 已经具备了基础条件。这里所指的产品、装备具有广义的概念，既包括制造业所生产的产品 和制造产线等，也包括能源、交通、农业、公共事业等行业提供服务时所依赖的资产，如电表、交通工具、 农业机械、环境监测仪器等。

-	边缘计算 （Edge Computing）	::	边缘计算是指在靠近物或数据源头的一侧，采用网络、计算、存储、应用核心能力为一体的开放平台，就近提供最近端服务。其应用程序在边缘侧发起，产生更快的网络服务响应，满足行业在实时业务、应用智能、安全与隐私保护等方面的基本需求。

-	云计算	（Cloud Computing） ::	云计算通常简称为“云”。通过互联网，“按使用量付费” 的方式 提供随需应变的计算资源（从应用到数据中心）。其部署方式包括 公有云、私有云和混合云。

-	深度学习	（Deep Learning） ::	深度学习的概念源于人工神经网络的研究。含多隐层的多层感知器就是一种深度学习结构。深度学习通过组合低层特征形成更加抽象的高层表示属性类别或特征，以发现数据的分布式特征表示。

-	数据挖掘	（Data Mining） ::	 数据挖掘一般是指从大量的数据中通过算法搜索隐藏于其中信息的过程。数据挖掘通常与计算机科学有关，并通过统计、在线分析处理、情报检索、机器学习、专家系统（依靠过去的经验法则）和模式识别等诸多方法来实现上述目标。

-	智能制造	（Intelligent Manufacturing） :: 智能制造应当包含智能制造技术和智能制造系统，智能制造系统不仅能够在实践中不断地充实知识库，而且还具有自学习功能，还有搜集与理解环境信息和自身的信息，并进行分析判断和规划自身行为的能力。

* 需求组

- 产品谱系追溯  (Product Pedigree Traceability) :: 采集整合原材料、在制品和产品服务/维护数据，基于统一编码标识实现完整的可追溯的产品谱系。

- 产品优化创新  (Product Optimization And Innovation) :: 对制造过程的生产数据和服务/维护过程 的产品数据进行采集和处理，然后反馈到产品设计过程中，在产品设计阶段优 化产品性能、创新产品功能。

- 协同设计  (Collaborative Design) :: 企业与企业之间,通过网络化的设计平台,分工并行开展的产品设计模式,可有效缩短产品设计周期。

- 协同制造 (Collaborative Manufacturing) :: 基于网络协同平台，将制造任务、订单信息分配给不同地域、不同规模的制造企业，将社会分散的制造资源、制造能 力在网络平台进行集聚共享，形成网络 化协同的生产组织模式。

- 数据治理 (Data Governance) :: 对数据资产管理活动行使权力和控制的活动集合（规划、监控和执行）。数据治理职能指导其他数据管理职能如何执行。数据治理制定正确的原则、政策、流程、操作规程，确保以正确的方式对数据和信息进行管理。

- 数据资产 (Data Asset) :: 是指由企业拥有或者控制的，能够为企业带来未来经济利益的，以物理或电子的方式记录的数据资源，如文件资料、电子数据等。在企业中，并非所有的数据都构成数据资产，数据资产是能够为企业产生价值的数据资源。

- 数据资产管理 (Data Asset Management) :: 指规划、控制和提供数据及信息资产的一组业务职能，包括开发、执行和监督有关数据的计划、政策、方案、项目、流程、方法和程序，从而控制、保护、交付和提高数据资产的价值。数据资产管理是需要充分融合业务、技术和管理，来确保数据资产保值增值。
- 元数据 (Metadata) :: 是描述数据的数据。元数据按用途不同分为技术元数据、业务数据和管理元数据。

- 数据流通 (Data flow) :: 数据流通可以定义为某些信息系统中存储的数据作为流通对象，按照一定的规则从供应方传递到需求方的过程。

- 生产过程优化  (Production Process Optimization) :: 通过分析产品质量、成本、能耗、效率、成材率等关键指标与工艺、设备参数之间的关系，优化产品设计和工艺。以实际的生产数据为基础，建立生产过程的仿真模型，优化生产流程。根据客户订单、生产线、库存、设备等数据预测市场和订单，优化库存和生产计划、排程。

- 服务快速反应  (Service Rapid Response) :: 通过设备的智能化，可以通过互联网获取用户的实时工况数据。当用户设备出现问题或异常时，帮助用户更快地发现问题、找到问题的原因。通过数据分析，构建基于规则或案例的故障预测系统，对用户设备状态进行预测、帮助用户更好地维护设备。

- 虚拟仿真 (Virtual Reality) :: 用一个系统模仿另一个真实系统的技术。虚拟仿真实际上是一种可创建和体验虚拟世界的计算机系统。此种虚拟世界由计算机生成，可以是现实世界的再现，亦可以是构想中的世界，用户可借助视觉、听觉及触觉等多种传感通道与虚拟世界进行自然的交互。

- 柔性制造 (Flexible Manufacturing) :: 柔性可以表述为两个方面一个方面是指生产能力的柔性反应能力，也就是机器设备的小批量生产能力。第二个方面，指的是供应链的敏捷和精准的反应能力。这种以消费者为导向的， 以需定产的方式对立的是传统大规模量产的生产模式。

- 产品全生命周期管理 (Product Lifecycle Management) :: 品全生命周期管理是指管理产品从需求、规划、设计、生产、经销、运行、使用、维修保养、直到回收再用处置的全生命周期中的信息与过程。它既是一门技术, 又是一种制造的理念。它支持并行设计、敏捷制造、协同设计和制造, 网络化制造等先进的设计制造技术。


* 技术与标准组

- OPC-UA (Open Platform Communications-Unified Architecture) :: OPC 基金会 (OPC Foundation) 发布的最新的数据通讯统一方法 :OPC 统一架构 (OPC UA)， 涵盖了 OPC 实时数据访问规范 (OPC DA)、OPC 历史数据访问规范 (OPC HDA)、OPC 报警事件访问规范 (OPC A&E) 和 OPC 安全协议 (OPC Security) 的不同方面， 但在其基础之上进行了功能扩展。

- OSI 安全体系结构 (OSI Security Architecture) :: OSI 安全体系结构是国际标准化组织（ISO）在对 OSI 开放系统互联环境的安全性深入研究的基础上提出的。它定义了为保证 OSI 参考模型的安全应具备 5 类安全服务，包括鉴别服务、访问控制、数据完整性、数据保密性和不可抵赖性，以及为实现这 5 类安全服务所应具备的 8 种安全机制，包括加密、数字签名、访问控制、数据完整性、鉴别交换、业务流填充、路由控制以及公证。

- 信息保障技术框架 (Information Assurance Technical Framework) :: 是美国国家安全局于 1998 年提出的，该框架提出保障信息系统安全应具备的三个核心要素，即人、技术和操作。其中，人这一要素包括保障人身安全、对人员进行培训、制定安全管理制度等，强调了人作为防护措施的具体实施者在安全防护中的重要地位。

- 标识解析技术 (Identification Parsing Technology) :: 标识及标识解析技术是实现产品追溯的核心关键。其中，工业互联网标识，就类似于互联网域名，赋予每一个产品、零部件、机器设备唯一的“身份证”，实现资源区分和管理；工业互联网标识解析，类似于互联网域名解析，可以通过产品标识查询存储产品信息的服务器地址，或者直接查询产品信息以及相关服务。

- 产品追溯编码技术 (Product Traceability Coding Technology) :: 产品追溯编码技术是对可溯源产品的编码格式进行数据结构定义、分配及管理的技术。编码的分配主体及数据结构是由编码命名体系本身的适用范围决定的。

- 产品追溯载体技术 (Product Traceability Carrier Technology) :: 产品追溯载体技术是承载方式及载体选择技术，包括一维条码、二维条码、RFID 标签、传感器等。

- 产品追溯发现技术 (Product Traceability Discovery Technology) :: 发现技术是产品实现全生命周期追溯的典型应用场景的核心。一个商品从制造到出现在消费者手里，需要经历生产、加工、物流、销售等多个环节，每个环节该商品标识都会留下信息，而每个环节都由不同管理主体管理。标识发现技术就是找到该商品标识留下信息的所有环节对应的标识，例如每个环节的信息服务器 IP 地址，这些信息服务器会记录该商品标识在本环节产生的相关信息。

- 标识解析技术 (Identification Parsing Technology) :: 标识及标识解析技术是实现产品追溯的核心关键。其中，工业互联网标识，就类似于互联网域名，赋予每一个产品、零部件、机器设备唯一的“身份证”，实现资源区分和管理；工业互联网标识解析，类似于互联网域名解析，可以通过产品标识查询存储产品信息的服务器地址，或者直接查询产品信息以及相关服务。

- 异构识别技术 (Heterogeneous Recognition Technology) :: 异构识别技术针对产品追溯编码不一致，全生命周期“一物多码”的现状，分析出当前产品追溯异构标识的编码规律及趋势，针对产品追溯异构标识识别的冲突问题，提出适用于现有工业互联网领域产品追溯异构标识识别的冲突检测模型及判定算法，为未来新的工业互联网异构标识编码制定提供防冲突策略，并针对已冲突异构标识设计后向兼容机制，最大程度解决产品追溯异构标识识别中的冲突问题。 "

- 交叉验证 (Cross-validation) :: 主要用于建模应用中，例如 PCR、PLS 回归建模中。在给定的建模样本中，拿出大部分样本进行建模型，留小部分样本用刚建立的模型进行预报，并求这小部分样本的预报误差，记录它们的平方加和。

- 信息通信技术 (ICT（Institute of Computing Technology）) :: ICT 是信息、通信和技术三个英文单词的词头组合(Information Communications Technology，简称 ICT) 。它是信息技术与通信技术相融合而形成的一个新的概念和新的技术领域。

- 对象标识符 (Object Identifier) :: 是由 ISO/IEC、ITU 国际标准组织共同提出的标识机制。OID 在全球得到广泛注册和使用。

- TCP/IP 协议 (Transmission Control Protocol/Internet Protocol) :: 联网协议（Internet Protocol Suite）是一个网络通信模型，以及一整个网络传输协议家族，为互联网的基础通信架构。它常被通称为 TCP/IP 协议族（英语：TCP/IP Protocol Suite，或 TCP/IP Protocols），简称 TCP/IP。因为该协议家族的两个核心协议：TCP（传输控制协议）和 IP（网际协议），为该家族中最早通过的标准。

- LwM2M 协议 (LightweightM2M) :: LwM2M 协议是一种轻量级的物联网设备管理协议，由国际标准组织 OMA（Open Mobile Alliance）制定。协议定义了终端设备和物联网服务平台/业务应用之间的接口标准，尤其适合工业领域的各种计量设备或仪表。此类设备通常是资源非常受限的嵌入式终端，无 UI 计算能力和网络通信能力都有限，而且数量巨大，种类众多，尤其需要一种通用的轻量级设备管理协议。

- 面向工业过程自动化的工业无线网络标准技术 (Wireless Networks for Industrial Automation Process Automation ) :: 面向工业过程自动化的工业无线网络标准技术)标准是中国工业无线联盟针对过程自动化领域制定的 WIA 子标准，是基于 IEEE 802.15.4 标准的用于工业过程测量、监视与控制的无线网络系统。

- 以太网控制自动化技术 (EtherCAT（Control Automation Technology）) :: 以太网控制自动化技术是一个开放架构，以以太网为基础的现场总线系统。EtherCAT 是确定性的工业以太网，最早是由德国的 Beckhoff 公司研发。

- Modbus 协议 (Modbus Protocol ) :: Modbus 是一种串行通信协议，是 Modicon 公司于 1979 年为使用可编程逻辑控制器（PLC）通信而发表。Modbus 已经成为工业领域通信协议的业界标准（De facto），并且现在是工业电子设备之间常用的连接方式。

-  增强机器类通信 (Enhanced Machine Type Communication ) ::  增强机器类通信是万物互联技术的一个重要分支，基于 LTE 协议演进而来，为了更加适合物与物之间的通信，也为了更低的成本，对 LTE 协议进行了裁剪和优化 eMTC 基于蜂窝网络进行部署，其用户设备通过支 1.4MHz 的射频和基带带宽，可以直接接入现有的 LTE 网络。eMTC 支持上下行最大 1Mbps 的峰值速率，可以支持丰富、创新的物联应用。


* 网络组

- 消息队列遥测传输（Message Queuing Telemetry Transport，缩略语：MQTT） :: ISO 标准(ISO/IEC PRF 20922)下基于发布/订阅范式的消息协议。它工作在 TCP/IP 协议族上，是为硬件性能低下的远程设备以及网络状况糟糕的情况下而设计的发布/订阅型消息协议。

- 软件定义网络 (Software Deﬁned Networking) :: SDN 是一种新型的网络架构，它将网络控制平面和转发平面分离， 采用集中控制替代原有分布式控制，并通过开放和可编程接口实现 “软件定义”。

- 实时以太网络 (Time-Sensitive Networking ) :: 国际标准组织 IEEE 制订了 TSN(Time-Sensitive Networking）系列标 准，针对实时优先级、时钟等关键服务定义了统一的技术标准，是 工业以太联接未来的发展方向。

- 互操作  (Interoperability) :: 是指两个或多个系统之间交换信息， 能够相互理解信息的含义，并 在操作上能够相互协同。

- 信息模型 (Information Model) :: 是对数据的语义提供概念、关系、约束、操作的模型化表示，实现 信息的可共享、可组织。

- 产品追溯 (Product Traceability) :: 产品追溯是指产品从制造、流通、消费到回收的整个生命周期过程中，利用标识技术记录和查询产品状态、属性、位置等信息的过程，其目的是全方位记录产品信息数据，促进企业内部信息系统之间、企业之间、企业和用户之间信息的有效共享，提高工业企业网络化、智能化水平。

- 信息孤岛 (Information Island) :: 信息孤岛是指相互之间在功能上不关联互助、信息不共享互换以及信息与业务流程和应用相互脱节的计算机应用系统。

- 关系型数据库  (Relational Database) :: 关系数据库，是建立在关系模型基础上的数据库，借助于集合代数等数学概念和方法来处理数据库中的数据。关系模型由关系数据结构、关系操作集合、关系完整性约束三部分组成。

- 时序数据库 (Temporal Database) :: 时间序列数据库主要用于指处理带时间标签（按照时间的顺序变化，即时间序列化）的数据，带时间标签的数据也称为时间序列数据。基于时间序列数据的特点，关系型数据库无法满足对时间序列数据的有效存储与处理，因此迫切需要一种专门针对时间序列数据来做优化的数据库系统，即时间序列数据库。

- 内存数据库 (Memory Database) :: 内存数据库抛弃了磁盘数据管理的传统方式，基于全部数据都在内存中重新设计了体系结构，并且在数据缓存、快速算法、并行操作方面也进行了相应的改进，所以数据处理速度比传统数据库的数据处理速度要快很多，一般都在 10 倍以上。内存数据库的最大特点是其“主拷贝”或“工作版本”常驻内存，即活动事务只与实时内存数据库的内存拷贝打交道。

- 工业防火墙 (Industrial Firewall) :: 工业防火墙指的是一个有软件和硬件设备组合而成、在内部网和外部网之间、专用网与公共网之间的边界上构造的保护屏障。防火墙是一种保护计算机网络安全的技术性措施，它通过在网络边界上建立相应的网络通信监控系统来隔离内部和外部网络，以阻挡来自外部的网络入侵。

- 骨干网络 (Backbone Network) :: 属于具有分布式网状拓扑结构的分组交换网络。信息以分组的形式通过由到达同一目的地的多个路径构成的网络传送。网络通过路由器(它按照分组的目的地路径将信息转发)相连。“网状拓扑结构”提供了冗余链路。如果某个链路出现故障,分组会避开此链路按其他路径选择路由。

- 时间敏感网络  (Time-Sensitive Network) :: 时间敏感网络 是一种具有有界传输时延、低传输抖动和极低数据丢失率的高质量实时传输网络。它基于标准以太网，凭借时间同步、数据调度、负载整形等多种优化机制，来保证对时间敏感数据的实时、高效、稳定、安全传输。

- 5G 网络 (5G Network) :: 5G 网络是控制和转发分离的网络，转发面更专注于业务数据的高效路由转发，具有简单、稳定和高性能等特性，以满足未来海量移动流量的转发需求。

- 根区文件 (Root Zoon File) :: 存储标识解析体系中最高层级映射的信息数据文件。

- 根服务器 (Root Server) :: 标识解析体中最高层级的服务器。

- 网络虚拟化 (Network Virtualization) :: 能够实现网络资源动态调配、动态管理的技术。

* 工业互联网平台组

- 智能工厂 (Intelligent Factory) :: 智能工厂是在数字化工厂的基础上，利用物联网、大数据、人工智能等新一代信息技术加强信息管理以及合理计划排程，同时集智能手段和智能系统等新兴技术于一体，构建高效、和服务，提高生产过程可控性、减少生产线人工干预，节能、绿色、环保、舒适的人性化工厂。

- 智能故障诊断 (Intelligent Fault Diagnosis) :: 对设备运行数据进行实时采集与处理分析，根据已设定的规则进行非法操作报警、设备异常报警、偏离预定位置报警等实时报警，以及故障远程诊断、维护，并相应与智能服务平台一键智能派工服务集成。

-  故障预测 (Fault Prediction) ::  故障预测。基于存储在大数据存储与分析平台中的数据，通过设备使用数据、工况数据、主机及配件性能数据、配件更换数据等设备与服务数据，进行设备故障、服务、配件需求的预测，为主动服务提供技术支撑，延长设备使用寿命，降低故障率。

- 知识自动化 (Knowledge Automation) :: 知识自动化，是一种可执行知识工作任务的智能软件系统。它除了包含传统的规则、推理和显性表达式之外，也对隐含知识、模式识别、群体经验等进行模型化，并借助软件化的方式，形成可执行的知识软件系统。这将大大解放知识工作者的重复性劳动。

- IT 网络  (IT Technology Network) :: 用于连接信息系统与终端的数据通信网络。
- OT 网络  (Operation Technology Network) :: 用于 连接生产现场设备与系统，实现自动控制的工业通讯网络。

- 现场总线  (Field Bus) :: 连接智能现场设备和自动化系统的数字 式、双向传输、多分支结构的通信网络。

- 基于模型的设计  (MBD(Model Based Definition)) :: 用集成的三维 实体模型来表达完整产品定义信息的方法体，它在三维实体模型上附加了产品的尺寸、公差信息，是一种更便于用户 理解且更具效率的产品信息定义方法。

- 基于模型的企业  (MBE(Model Based Enterprise)) :: 采用建模与仿 真技术对设计、制造、产品支持的全部 技术的和业务的流程进行彻底的改进、 无缝的集成以及战略的管理，利用产品 和过程模型来定义、执行、控制和管理 企业的全部过程。

- 企业资源计划管理系统 (ERP (Enterprise Resource Planning)) :: 企业资源计划是指建立在信息技术基础上，以系统化的管理思想，为企业决策层及员工提供决策运行手段的管理平台。ERP 系统支持离散型、流程型等混合制造环境，应用范围从制造业扩展到了零售业、服务业、银行业、电信业、政府机关和学校等事业部门，通过融合数据库技术、图形用户界面、第四代查询语言、客户服务器结构、计算机辅助开发工具、可移植的开放系统等对企业资源进行了有效的集成。

- 人力资源管理系统 (HCM(Human Resources System)) :: 通过提高内部员工的满意度、忠诚度，从而提高员工贡献度，即绩效，帮助管理者通过有效组织管理降低成本和加速增长来创造价值链利润。人力资源综合管理解决方案从人力资源管理的角度出发，用集中的数据将几乎所有与人力资源相关的信息统一管理起来。

- 业务流程管理系统 (BPM(Business Process Management)) :: 业务流程管理系统是一种以规范化的构造端到端的卓越业务流程为中心，以持续的提高组织业务绩效为目的的系统化方法。

- 制造执行系统 (MES(Manufacturing Execution System)) :: 制造企业生产过程执行管理系统是一套面向制造企业车间执行层的生产信息化管理系统。MES 可以为企业提供包括制造数据管理、计划排程管理、生产调度管理、库存管理、质量管理、人力资源管理、工作中心/设备管理、工具工装管理、采购管理、成本管理、项目看板管理、生产过程控制、底层数据集成分析、上层数据集成分解等管理模块，为企业打造一个扎实、可靠、全面、可行的制造协同管理平台。

- 客户关系管理系统 (CRM(Customer Relationship Management)) :: 通常所指的 CRM，指用计算机自动化分析销售、市场营销、客户服务以及应用等流程的软件系统。它的目标是通过提高客户的价值、满意度、赢利性和忠实度来缩减销售周期和销售成本、增加收入、寻找扩展业务所需的新的市场和渠道。CRM 是选择和管理有价值客户及其关系的一种商业策略，CRM 要求以客户为中心的企业文化来支持有效的市场营销、销售与服务流程。

- SCADA 系统 (upervisory Control And Data Acquisition) :: SCADA 系统是以计算机为基础的生产过程控制与调度自动化系统。它可以对现场的运行设备进行监视和控制。应用于电力、冶金、石油、化工、燃气、铁路等领域的数据采集与监视控制以及过程控制等诸多领域。

- 现场级 (Work Cell) :: 由企业确定的一个物质的、地理的或逻辑的生产群组，完成的某项工序活动。

* 测试床组

- 关联分析 (Association Analysis) :: 关联分析又称关联挖掘，就是在交易数据、关系数据或其他信息载体中，查找存在于项目集合或对象集合之间的频繁模式、关联、相关性或因果结构。

- 数字化双胞胎 (Digital Twins) :: “数字化双胞胎”是指以数字化方式拷贝一个物理对象，模拟对象在现实环境中的行为，对产品、制造过程乃至整个工厂进行虚拟仿真，从而提高制造企业产品研发、制造的生产效率。

- 信息物理系统 (Cyber-Physical Systems) :: 信息物理系统是一个综合计算、网络和物理环境的多维复杂系统，通过 3C（Computer、Communication、Control）技术的有机融合与深度协作，实现大型工程系统的实时感知、动态控制和信息服务。CPS 实现计算、通信与物理系统的一体化设计，可使系统更加可靠、高效、实时协同，具有重要而广泛的应用前景。

- 物联网 (Internet Of Things) :: 物联网就是物物相连的互联网。这有两层意思：其一，物联网的核心和基础仍然是互联网，是在互联网基础上的延伸和扩展的网络；其二，其用户端延伸和扩展到了任何物品与物品之间，进行信息交换和通信，也就是物物相息。物联网通过智能感知、识别技术与普适计算等通信感知技术，广泛应用于网络的融合中，也因此被称为继计算机、互联网之后世界信息产业发展的第三次浪潮。

- 区块链 (Blockchain) :: 区块链是分布式数据存储、点对点传输、共识机制、加密算法等计算机技术的新型应用模式。区块链技术是利用块链式数据结构来验证与存储数据、利用分布式节点共识算法来生成和更新数据、利用密码学的方式保证数据传输和访问的安全、利用由自动化脚本代码组成的智能合约来编程和操作数据的一种全新的分布式基础架构与计算方式

- 人工智能 (Artificial Intelligence) :: 它是研究、开发用于模拟、延伸和扩展人的智能的理论、方法、技术及应用系统的一门新的技术科学。它企图了解智能的实质，并生产出一种新的能以人类智能相似的方式做出反应的智能机器，该领域的研究包括机器人、语言识别、图像识别、自然语言处理和专家系统等。

- SaaS 服务 (Software As A Service) :: SaaS 是 Software-as-a-Service（软件即服务）的简称。是一种通过 Internet 提供软件的模式，厂商将应用软件统一部署在自己的服务器上，客户可以根据自己实际需求，通过互联网向厂商定购所需的应用软件服务，按定购的服务多少和时间长短向厂商支付费用，并通过互联网获得厂商提供的服务。

- PaaS 服务 (Platform As A Service) :: PaaS 是位于 IaaS 和 SaaS 模型之间的一种云服务，它提供了应用程序的开发和运行环境。IaaS 主要提供了虚拟计算、存储、数据库等基础设施服务，SaaS 为用户提供了基于云的应用，PaaS 则为开发人员提供了构建应用程序的环境。借助于 PaaS 服务，你无须过多的考虑底层硬件，并可以方便的使用很多在构建应用时的必要服务，比如安全认证等。

- 功能设计视图 (Functional Design View) :: 阐述横向的开发服务框架、部署运营框架业务 Fabric、联接计算 Fabric 和 ECN，纵向的跨层次开放服务、 管理服务、数据全生命周期服务、安全服务的功能与设计思路。

- 部署视图 (Deployment View) :: 阐述系统的部署过程和典型的部署场景。同时，架构需要满足跨行业的典型非功能性需求，包括实时性、确定性、可靠性等。为此，在功能视 图、部署视图给出了相关技术方案推荐。

- EVF 层 (Edge Virtualization Function) :: EVF 是将功能软件化和服务化，并且与专有的硬件平台解耦。基于虚拟化技术，在同一个硬件平台上，可 以纵向将硬件、系统和特定的 EVF 等按照业务进行组合，虚拟化出多个独立的业务区间并彼此隔离。EVF 可以灵活组合与编排，能够在不同硬件平台、不同设备上灵活迁移和弹 0 性扩展，实现资源的动态调度 和业务敏捷。

- 软件定义网络 (Software Definition Network) :: SDN 采用与传统网络截然不同的控制架构，将网络控制平面和转发平面分离，采用集中控制替代原有分 布式控制，并通过开放和可编程接口实现“软件定义”。SDN 不仅是新技术，而且变革了网络建设和运营的方 式：从应用的角度构建网络，用 IT 的手段运营网络。SDN 架构包括控制器、南/北向接口、以及应用层的各类应用和基础设施层的各种网元。其中最重要的是 SDN 控制器，它实现对基础设施层的转发策略的配置和管理，支持基于多种流表的转发控制。

- 异构计算 (Heterogeneous Computing) :: 异构计算目标是整合同一个平台上分立的处理单元使之成为紧密协同的整体来协同处理不同类型的计算 负荷。同时通过开放统一的编程接口，实现软件跨多种平台。协同和发挥各种计算单元的独特优势。

- 业务 Fabric  (Business Fabric ) :: 业务 Fabric 是模型化的工作流，由多种类型的功能服务按照一定逻辑关系组成和协作，实现特定的业务 需求，是对业务需求的数字化表示。服务的模型，包括服务名称、执行或提供什么样的功能，服务间的嵌套、依赖、继承等关系，每个服务 的输入与输出，以及 Qos、安全、可靠性等服务约束。服务的类型不仅包括边缘计算提供的通用服务，还包括垂直行业所定义的特定行业服务。

- 数据预处理 (Data Preprocessing) :: 对原始数据的过滤、清洗、聚合、质量优化（剔除坏数据等）和语义解析。

* 产业发展组

- 智慧城市 (Smart City) :: 利用各种信息技术或创新意念，集成城市的组成系统和服务，以提升资源运用的效率，优化城市管理和服务，以及改善市民生活质量。智慧城市把新一代信息技术充分运用在城市的各行各业之中的基于知识社会下一代创新（创新 2.0）的城市信息化高级形态，实现信息化、工业化与城镇化深度融合，有助于缓解“大城市病”，提高城镇化质量，实现精细化和动态管理，并提升城市管理成效和改善市民生活质量。

- 智能交通系统 (Intelligent Transportation System) :: 智能交通系统是将先进的信息技术、数据通讯传输技术、电子传感技术、控制技术及计算机技术等有效地集成运用于整个地面交通管理系统而建立的一种在大范围内、全方位发挥作用的，实时、准确、高效的综合交通运输管理系统。

- 智慧能源 (Smarter Energy) :: 智慧能源就是充分开发人类的智力和能力，通过不断技术创新和制度变革，在能源开发利用、生产消费的全过程和各环节融汇人类独有的智慧，建立和完善符合生态文明和可持续发展要求的能源技术和能源制度体系，从而呈现出的一种全新能源形式。简而言之，智慧能源就是指拥有自组织、自检查、自平衡、自优化等人类大脑功能，满足系统、安全、清洁和经济要求的能源形式。

* 频谱组

- RFID 定位技术  (RFID Location Technology) :: RFID 定位是采用射频识别技术，通过 RFID 信号识别终端的定位技术。该定位由阅读器获取终端数据，采用 RSSI 或者 TDOA 计算方法，实现终端位置的计算。

- UWB 定位技术  (UWB Location Technology) :: UWB 定位是采用超带宽无线通信的定位技术。所谓超带宽通信，是指通过发送和接收纳秒或纳秒级以下的极窄脉冲传输数据，从而具有 GHz 带宽的无线通信技术。

- 正交频分复用技术 (Orthogonal Frequency Division Multiplexing OFDM) :: 将信道分成若干正交子信道，将高速数据信号转换成并行的低速子数据流，调制到在每个子信道上进行传输。正交信号可以通过在接收端采用相关技术来分开，这样可以减少子信道之间的相互干扰 ISI(Intersymbol Interference) 。每个子信道上的信号带宽小于信道的相关带宽，因此每个子信道上的可以看成平坦性衰落，从而可以消除符号间干扰。而且由于每个子信道的带宽仅仅是原信道带宽的一小部分，信道均衡变得相对容易。

- 多入多出技术 (Multiple-Input Multiple-Output) :: 指在发射端和接收端分别使用多个发射天线和接收天线，使信号通过发射端与接收端的多个天线传送和接收，从而改善通信质量。它能充分利用空间资源，通过多个天线实现多发多收，在不增加频谱资源和天线发射功率的情况下，可以成倍的提高系统信道容量，显示出明显的优势、被视为下一代移动通信的核心技术。

- 码分多址技术 (Code Division Multiple Access) :: 码分多址(CDMA)是在数字技术的分支--扩频通信技术上发展起来的一种崭新而成熟的无线通信技术。CDMA 技术的原理是基于扩频技术，即将需传送的具有一定信号带宽信息数据，用一个带宽远大于信号带宽的高速伪随机码进行调制，使原数据信号的带宽被扩展，再经载波调制并发送出去。接收端使用完全相同的伪随机码，与接收的带宽信号作相关处理，把宽带信号换成原信息数据的窄带信号即解扩，以实现信息通信。

- 射频识别 (Radio Frequency Identification) :: 是一种通信技术，可通过无线电讯号识别特定目标并读写相关数据，而无需识别系统与特定目标之间建立机械或光学接触。

* 国际合作与对外交流组

- 工业 4.0 (Industry 4.0) :: 工业 4.0 则是利用信息化技术促进产业变革的时代，也就是智能化时代。这个概念最早出现在德国，旨在提升制造业的智能化水平，建立具有适应性、资源效率及基因工程学的智慧工厂，在商业流程及价值流程中整合客户及商业伙伴。其技术基础是网络实体系统及物联网。

- 中国工业互联网产业联盟  (AII(Alliance Of Industrial Inernet)) :: “工业互联网产业联盟”接受工业和信息化部业务指导，中国信息通信研究院是联盟理事长单位。联盟还包括航天科工、中国电信、海尔、华为等 9 家副理事长单位。

- 美国工业互联网联盟 (IIC(Industrial Internet Consortium)) :: 由 AT&T、思科(Cisco)、通用电气(GE)、IBM 和英特尔(intel)在美国波士顿成立工业互联网联盟(IIC)，以期打破技术壁垒，通过促进物理世界和数字世界的融合。

- 物联网创新联盟 (IOTIA(Internet of Things Innovation Alliance)) :: 该联盟由世界华商联盟会、世界物联网大会组委会、中国物联网发展基金筹委会、中国新媒体行业联合会等共同发起，定位于非赢利性、服务型组织。旨在让各路创业精英、创新企业、转型企业深度了解中国与全球物联网新兴经济，把握未来物联网时代的契机，推动物联网产业发展。

- 电气和电子工程师协会 (IEEE(Institute of Electrical and Electronics Engineers)) :: 电气和电子工程师协会是一个国际性的电子技术与信息科学工程师的协会，是目前全球最大的非营利性专业技术学会，其会员人数超过 40 万人，遍布 160 多个国家。IEEE 致力于电气、电子、计算机工程和与科学有关的领域的开发和研究，在太空、计算机、电信、生物医学、电力及消费性电子产品等领域已制定了 900 多个行业标准，现已发展成为具有较大影响力的国际学术组织。

* 垂直行业组

* 政策法规和投融资特设组

- 工业 APP :: 面向特定工业应用场景，开发者通过调用工业互联网云平台的资源，推动工业技术、经验、知识和最佳实践模型化、软件化、再封装而形成的应用程序。

- IPv6 :: Internet Protocol Version 6 的缩写，即互联网协议版本 6，是互联网协议的一个新版本。

- 无源光网络（Passive Optical Network, 缩略语 PON） :: 一个无源光网络包括一个安装于中心控制站的光线路终端（OLT），以及一批配套的安装于用户场所的光网络单元（ONUs）；在 OLT 与 ONU 之间的光配线网（ODN）全部由光分路器等无源器件组成，不需要有源电子设备。

- 软件定义网络（Software-Defined Networking, 缩略语:SDN） :: 一种网络控制和转发分离的网络架构，上层应用和服务可通过网络控制层的可编程接口实现对底层网络设备的控制。

- 窄带物联网（NB-IoT） :: 物联网领域的一项新兴技术，支持低功耗设备在广域网的蜂窝数据连接，也被叫作低功耗广域网。

- 时间敏感网络（Time Sensitive Network, 缩略语:TSN） :: TSN 是一种面向 1000Mbps 以及更高速率以太网接口的网络技术，它以太网技术为主体，包含了时序控制和时间同步、路径控制和预留、流量调度、帧抢占和流量预留、转发控制增强等多个局域网和城域网的桥接网络技术点。

- 边缘计算（Edge Computing） :: 边缘计算是在靠近物或数据源头的网络边缘侧，融合网络、计算、存储、应用核心能力的分布式开放平台，就近提供边缘智能服务，满足行业数字化在敏捷联接、实时业务、数据优化、应用智能、安全与隐私保护等方面的关键需求。

- 人工智能（Artificial Intelligence, 缩略语:AI） :: 研究开发用于模拟、延伸和扩展人类智能的理论、方法、技术及应用系统的一门新技术科学。

- 工业大数据 :: 在工业领域中围绕典型智能制造模式，从客户需求到销售、订单、计划、研发、设计、工艺、制造、采购、供应、库存、发货和交付、售后服务、运维、报废或回收再制造等整个产品全生命周期各环节，所产生的各类数据及相关技术和应用的总称。

- 虚拟现实 :: 借助计算机系统及传感器技术生成一种模拟环境，通过交互式的三维动态视景和实体行为仿真，使用户沉浸到该环境中。

- 增强现实 :: 通过将三维内容投射到某介质上，呈现真实的人、场景与虚拟物体结合效果，与虚拟现实最大的不同是其中多了现实世界的东西，现实与虚拟融合。

- 混合现实（Mixed Reality, 缩略语：MR） :: 混合现实技术（MR）是虚拟现实技术的进一步发展，该技术通过在虚拟环境中引入现实场景信息，在虚拟世界、现实世界和用户之间搭起一个交互反馈的信息回路，以增强用户体验的真实感。

- 区块链（Blockchain） :: 分布式数据储存、点对点传输、共识机制、加密算法等计算机技术的新型应用模式。

- OPC 统一架构（OPC Unified Architecture） :: OPC 基金会（OPC Foundation）创建的新技术，更加安全、可靠、中立（与供应商无关），为制造现场到生产计划或企业资源计划（ERP）系统传输原始数据和预处理信息。
