# 工业互联网术语和定义

新增加条目格式：

- 软件定义网络（Software Defined Network, 缩略语:SDN） :: 一种网络控制和转发分离的网络架构，上层应用和服务可通过网络控制层的可编程接口实现对底层网络设备的控制。

* 总体组

- 工业互联网（Industrial Internet, II） :: 工业互联网是满足工业智能化发展需求，具有低时延、高可靠、广覆盖特点的关键网络基础设施，是新一代信息通信技术与先进制造业深度融合所形成的新兴业态与应用模式。

- 工业互联网标识解析 :: 工业互联网标识通过赋予每一个产品、零部件、机器设备唯一的“身份证”，实现全网资源的灵活区分和信息管理。工业互联网标识解析类似于互联网域名解析，可以通过产品标识查询储存产品信息的服务器地址，或者查询产品信息以及相关服务。

- 工业互联网平台 :: 指面向制造业数字化、网络化、智能化需求，构建基于海量数据采集、汇聚、分析的服务体系，支撑制造资源泛在连接、弹性供给、高效配置的工业云平台。

* 需求组

* 技术与标准组

* 网络组

* 工业互联网平台组

* 测试床组

* 产业发展组

* 频谱组

* 国际合作与对外交流组

* 垂直行业组

* 政策法规和投融资特设组

- 工业 APP :: 面向特定工业应用场景，开发者通过调用工业互联网云平台的资源，推动工业技术、经验、知识和最佳实践模型化、软件化、再封装而形成的应用程序。

- IPv6 :: Internet Protocol Version 6 的缩写，即互联网协议版本 6，是互联网协议的一个新版本。

- 无源光网络（Passive Optical Network, 缩略语 PON） :: 一个无源光网络包括一个安装于中心控制站的光线路终端（OLT），以及一批配套的安装于用户场所的光网络单元（ONUs）；在 OLT 与 ONU 之间的光配线网（ODN）全部由光分路器等无源器件组成，不需要有源电子设备。

- 软件定义网络（SDN） :: 一种网络控制和转发分离的网络架构，上层应用和服务可通过网络控制层的可编程接口实现对底层网络设备的控制。

- 窄带物联网（NB-IoT） :: 物联网领域的一项新兴技术，支持低功耗设备在广域网的蜂窝数据连接，也被叫作低功耗广域网。

- 时间敏感网络（TSN） :: TSN 是一种面向 1000Mbps 以及更高速率以太网接口的网络技术，它以太网技术为主体，包含了时序控制和时间同步、路径控制和预留、流量调度、帧抢占和流量预留、转发控制增强等多个局域网和城域网的桥接网络技术点。

- 边缘计算（Edge Computing） :: 边缘计算是在靠近物或数据源头的网络边缘侧，融合网络、计算、存储、应用核心能力的分布式开放平台，就近提供边缘智能服务，满足行业数字化在敏捷联接、实时业务、数据优化、应用智能、安全与隐私保护等方面的关键需求。

- 人工智能（Artificial Intelligence, 缩略语:AI） :: 研究开发用于模拟、延伸和扩展人类智能的理论、方法、技术及应用系统的一门新技术科学。

- 工业大数据 :: 在工业领域中围绕典型智能制造模式，从客户需求到销售、订单、计划、研发、设计、工艺、制造、采购、供应、库存、发货和交付、售后服务、运维、报废或回收再制造等整个产品全生命周期各环节，所产生的各类数据及相关技术和应用的总称。

- 虚拟现实 :: 借助计算机系统及传感器技术生成一种模拟环境，通过交互式的三维动态视景和实体行为仿真，使用户沉浸到该环境中。

- 增强现实 :: 通过将三维内容投射到某介质上，呈现真实的人、场景与虚拟物体结合效果，与虚拟现实最大的不同是其中多了现实世界的东西，现实与虚拟融合。

- 混合现实 :: 混合现实技术（MR）是虚拟现实技术的进一步发展，该技术通过在虚拟环境中引入现实场景信息，在虚拟世界、现实世界和用户之间搭起一个交互反馈的信息回路，以增强用户体验的真实感。

- 区块链 :: 分布式数据储存、点对点传输、共识机制、加密算法等计算机技术的新型应用模式。

- OPC 统一架构（OPC Unified Architecture） :: OPC 基金会（OPC Foundation）创建的新技术，更加安全、可靠、中立（与供应商无关），为制造现场到生产计划或企业资源计划（ERP）系统传输原始数据和预处理信息。
