#+TITLE: 工业互联网术语和定义白皮书
#+AUTHOR: 工业互联网产业联盟
#+LATEX_CLASS: cn-article
#+LaTeX_HEADER: \linespread{1.5}

* 工业互联网（Industrial Internet）

工业互联网是满足工业智能化发展需求，具有低时延、高可靠、广覆盖特点的关键网络基础设施，是新一代信息通信技术与先进制造业深度融合所形成的新兴业态与应用模式。

* 工业互联网平台（Industrial Internet Platform）

工业互联网平台是面向制造业数字化、网络化、智能化需求，构建基于海量数据采集、汇聚、分析的服务体系，支撑制造资源泛在连接、弹性供给、高效配置的工业云平台。

* 工业 APP（Industrial Applications）

工业 APP 是工业软件发展的新形态，本质是工业知识的软件化，将隐性、分散的知识显性化、公有化、组织化、系统化，促进知识沉淀、传播与复用，提升知识价值创造，改变知识生产方式。工业 APP 是工业互联网平台的最终价值体现，支撑工业互联网平台智能化应用。工业 APP 在工业互联网环境下开发、应用及共享有利于促进知识的传播与复用，把知识经济推向新的时代。

* 工业大数据（Industrial Big Data）

工业大数据即工业数据的总和，即企业信息化数据、工业物联网数据，以及外部跨界数据。其中，企业信息化和工业物联网中机器产生的海量时序数据是工业数据规模变大的主要来源。

* 工业大数据平台（Industrial Big Data Platform）

工业大数据平台是采用分布式存储和计算技术，提供工业大数据的访问和处理，提供异构工业数据的一体化管理能力，支持工业大数据应用安全高效运行的软硬件集合。

* 工业大数据参考架构（Reference Architecture of Industrial Big Data）

工业大数据参考架构是以工业过程的业务需求为导向，基于工业系统的业务架构，规划工业大数据的数据、技术和应用（平台）架构，以搭建面向多业务领域、贯通多组织和应用层次的工业大数据 IT 架构。

* 工业大数据建模与分析（Industrial Big Data Modeling and Analysis）

工业大数据建模与分析通过工业大数据构建制造业快速迭代、持续优化、数据驱动的新方式，解决发生了什么、为什么发生、下一步发生什么、如何改进优化四个问题，优化制造资源的配置效率。工业大数据建模与分析需要整合不同学科、不同领域的经验、知识和技术。典型的工业大数据建模与分析的应用场景包括：预测性的维护、半监督学习、数据驱动的能源管理和设备管理等。

* 工业互联网标识解析体系（Identification and Resolution System of Industrial Internet）

工业互联网标识解析体系是工业互联网网络体系的重要组成部分，是支撑工业互联网互联互通的神经枢纽，其作用就类似于互联网领域的域名解析系统（DNS）。工业互联网标识解析体系的核心包括标识编码和解析系统两部分。

* 工业互联网开源软件（Open Source Software of Industrial Internet）

工业互联网开源软件是应用于工业互联网体系架构中的，按一定规则和协议实现源代码对开发者开放的软件。

* 工业互联网开源社区（Open Source Community of Industrial Internet）

工业互联网开源社区是为工业互联网开源软件开发者搭建的开发、使用、交流开源软件和技术的网络平台。

* 工业互联网安全态势感知（Security Situation Awareness of Industrial Internet）

工业互联网安全态势感知是通过采集工业互联网流量、资产、日志、告警、安全处置数据和第三方数据，利用统计分析和数据挖掘等方法，分析工业互联网的网络行为及用户行为，识别能引起工业互联网态势变化的安全要素，从而展示整个网络当前安全状态，并预测未来发展趋势。

* 工业互联网资产（Industrial Internet Assets）

工业互联网资产对工业互联网业务具有价值的信息或资源，是安全策略保护的对象。

* 工业微服务（Industrial Microservice）

工业微服务是工业互联网平台中知识沉淀和复用的载体。微服务是以单一功能组件为基础，通过模块化组合方式实现“松耦合”应用开发的软件架构。工业微服务实现机理模型算法的集成，支撑工业互联网平台中的工业 APP 开发运行。工业微服务本质是经验知识的软件化和工具化，借助专业化的工具打造通用化的平台。工业微服务支撑工业互联网平台进行工业体系颠覆创新，主要体现在颠覆传统工业软件研发方式、打破工业知识封闭传承体系和创造全新平台开放价值生态。

* 工业智能（Industrial Intelligence）

或称工业人工智能（Industrial Artificial Intelligence），是工业领域中由计算机实现的具有自感知、自学习、自执行、自决策、自适应等特征的应用。

* 工业 4.0(Industry 4.0)

工业 4.0 由德国提出，旨在提升制造业的智能化水平，建立具有适应性、资源效率及基因工程学的智慧工厂，在商业流程及价值流程中整合客户及商业伙伴。

* 业务流程管理系统 (Business Process Management, BPM)

业务流程管理系统是一种以规范化的构造端到端的卓越业务流程为中心，以持续的提高组织业务绩效为目的的系统化方法。

* 客户关系管理系统 (Customer Relationship Management, CRM)

客户关系管理系统是指用计算机自动化分析销售、市场营销、客户服务以及应用等流程的软件系统。它的目标是通过提高客户的价值、满意度、赢利性和忠实度来缩减销售周期和销售成本、增加收入、寻找扩展业务所需的新的市场和渠道。CRM 是选择和管理有价值客户及其关系的一种商业策略，CRM 要求以客户为中心的企业文化来支持有效的市场营销、销售与服务流程。

* 企业资源计划管理系统 (Enterprise Resource Planning, ERP)

企业资源计划是指建立在信息技术基础上，以系统化的管理思想，为企业决策层及员工提供决策运行手段的管理平台。

* 制造执行系统 (Manufacturing Execution System, MES)

制造执行系统是一套面向制造企业车间执行层的生产信息化管理系统。MES 可以为企业提供包括制造数据管理、计划排程管理、生产调度管理、库存管理、质量管理、人力资源管理、工作中心/设备管理、工具工装管理、采购管理、成本管理、项目看板管理、生产过程控制、底层数据集成分析、上层数据集成分解等管理模块，为企业打造一个扎实、可靠、全面、可行的制造协同管理平台。

* 供应链管理（Supply Chain Management, SCM）

供应链管理是在满足一定的客户服务水平的条件下，为了使整个供应链系统成本达到最小而把供应商、制造商、仓库、配送中心和渠道商等有效地组织在一起来进行的产品制造、转运、分销及销售的管理方法。

* 工业通信协议（Industrial Communication Protocol）

工业通信协议是指工业控制领域的双方实体完成通信或服务所必须遵循的规则和约定。通过通信信道和设备互连起来的多个不同地理位置的数据通信系统，要使其能协同工作实现信息交换和资源共享，它们之间必须具有共同的语言。交流什么、怎样交流及何时交流，都必须遵循某种互相都能接受的规则，这个规则就是工业通信协议。常见的工业通信协议包括 ModBus、OPC-UA、CAN 等。

* 高性能计算芯片（High Performance Computing Microchip）

高性能计算芯片指在多处理器或者集群计算系统和环境下的半导体设备，即面向高性能计算的芯片组。基于摩尔定律的描述,集成电路的集成度在不断上升,同时特征尺寸也在不断下降。特别是进入纳米及超高速发展的时代以来,电路的设计方法也由最初的全定制设计到后来的基于单元库的半定制设计,现在已经演变为基于 IP 核的 SOC（System On Chip）系统设计。工业互联网平台需要大量的芯片，包括感测芯片、计算芯片等。

* 数据采集与监控系统 (Supervisory Control And Data Acquisition, SCADA)

数据采集与监控系统是以计算机为基础的生产过程控制与调度自动化系统。它可以对现场的运行设备进行监视和控制。应用于电力、冶金、石油、化工、燃气、铁路等诸多领域。SCADA 作为工业互联网平台上的一个重要应用系统，是平台数据来源的重要一环，肩负着数据采集、测量、各类信号报警、设备控制以及参数调节等功能。

* 产品数据管理（Product Data Management, PDM）

产品数据管理是服务于产品研发参与企业的集成协同设计管理系统，为企业提供产品研发项目管控、产品数据全生命周期管理、企业设计和工程资源体系管理等应用，助力企业实现以产品为中心的基于图文档、设计模型、BOM 和技术状态管理的全面设计协同管理。通过与企业 ERP 和 MES 系统的集成，实现产品研发设计价值链与上下游参与企业的全面协同。

* 边缘数据处理（Edge Data Processing）
边缘数据处理是指在边缘层进行数据的预处理和缓存，即广义的“边缘计算”。工业生产过程中高频数据采集，往往会对网络传输、平台存储与计算处理等方面带来性能和成本上的巨大压力，边缘数据处理目前正成为主要平台企业的共同做法。一是在边缘层进行数据预处理，剔除冗余数据，减轻平台负载压力；二是利用边缘缓存保留工业现场全量数据，并通过缓存设备直接导入数据中心，降低网络使用成本。
* 边缘虚拟功能(Edge Virtualization Function, EVF)
边缘虚拟功能（EVF）是将功能软件化和服务化，并且与专有的硬件平台解耦。基于虚拟化技术，在同一个硬件平台上，可以纵向将硬件、系统和特定的 EVF 等按照业务进行组合，虚拟化出多个独立的业务区间并彼此隔离。EVF 可以灵活组合与编排，能够在不同硬件平台、不同设备上灵活迁移和弹性扩展，实现资源的动态调度 和业务敏捷。
* IT 网络 (Information Technology Network)
用于连接信息系统与终端的数据通信网络。
* 轻量级 M2M 协议 (Light Weight M2M Protocol，LwM2M)
LwM2M 协议是一种轻量级的物联网设备管理协议，由国际标准组织 OMA（Open Mobile Alliance）制定。
* Modbus 协议(Modbus Protocol )
Modbus 是一种串行通信协议，是 Modicon 公司于 1979 年为使用可编程逻辑控制器（PLC）通信而发表。Modbus 已经成为工业领域通信协议的业界标准（De facto），并且现在是工业电子设备之间常用的连接方式。
* OPC 统一架构(Open Platform Communications-Unified Architecture, OPU-UA)
OPC 是自动化行业及其他行业用于数据安全交换时的互操作性标准。它独立于平台，并确保来自多个厂商的设备之间信息的无缝传输，OPC 基金会负责该标准的开发和维护。OPC-UA 是在 OPC 技术的基础上，由 OPC 基金会在 2008 年发布的面向服务的数据通讯技术架构，将 OPC 实时数据访问规范(OPC DA)、OPC 历史数据访问规范 (OPC HDA)、OPC 报警事件访问规范 (OPC A&E)、OPC 安全协议 (OPC Security)等 OPC 功能统一集成在架构中，更具安全性、可靠性、高可用性、平台独立性和可伸缩性。
* OSI 安全体系结构 (Open System Interconnection Security Architecture)
OSI（开放式系统互联）安全体系结构由国际标准化组织（ISO）提出，它定义了为保证 OSI 参考模型的安全应具备 5 类安全服务，包括鉴别服务、访问控制、数据完整性、数据保密性和不可抵赖性，以及为实现这 5 类安全服务所应具备的 8 种安全机制，包括加密、数字签名、访问控制、数据完整性、鉴别交换、业务流填充、路由控制以及公证。
* OT 网络 (Operation Technology Network)
用于连接生产现场设备与系统，实现自动控制的工业通讯网络。
* 平台即服务 (Platform as a Service, PaaS )
PaaS 平台即把应用服务的运行和开发环境作为一种服务提供的商业模式。PaaS 是位于 IaaS 和 SaaS 模型之间的一种云服务，它提供了应用程序的开发和运行环境，借助于 PaaS 服务，你无须过多的考虑底层硬件，并可以方便的使用很多在构建应用时的必要服务。PaaS 能将现有各种业务能力进行整合，具体可以归类为应用服务器、业务能力接入、业务引擎、业务开放平台，向下根据业务能力需要测算基础服务能力，通过 IaaS 提供的 API 调用硬件资源，向上提供业务调度中心服务，实时监控平台的各种资源，并将这些资源通过 API 开放给 SaaS 用户。
* 软件即服务 (Software as a Service, SaaS)
软件即服务（SaaS）是一种通过 Internet 提供软件的模式，厂商将应用软件统一部署在自己的服务器上，客户可以根据自己实际需求，通过互联网向厂商定购所需的应用软件服务，按定购的服务多少和时间长短向厂商支付费用，并通过互联网获得厂商提供的服务。
* 超宽带定位技术 (Ultra Wideband Location Technology)
超宽带（UWB）定位技术是采用超带宽无线通信的定位技术，其中超带宽通信是指通过发送和接收纳秒或纳秒级以下的极窄脉冲传输数据，从而具有 GHz 带宽的无线通信技术。
* 安全策略（Security Policy）
安全策略是关于如何在组织及其系统内管理、保护和分发资产(包括敏感信息)的规则、指令和实践，特别是影响到系统和相关要素的规则、指令和实践。
* 安全措施（Security Measure）
安全措施是为了保护资产、抵御威胁、减少脆弱性、降低安全事件的影响，以及打击信息犯罪而实施的各种实践、规程和机制。
* 安全服务 （Security Service）
安全服务是根据安全策略为用户提供的某种安全功能及相关的保障。
* 安全可控（Securable Control）
安全可控是指从组织、用户和国家三个角度确保工业互联网业务运行安全、用户能选择和控制工业互联网业务，并控制自己的信息，监控部门能控制工业互联网业务带来的国家安全风险。
* 安全事件态势（Security Incident Situation）
安全事件态势是通过解析还原工业设备所使用的各类通信协议网络数据流，检测分析工业协议数据恶意攻击行为，从这些行为中分析出安全事件，并对安全事件进行多维度（发生时间、地域、威胁类型、关联资产等）分类处理和趋势展示。
* 安全域（Security Zone）
安全域是具有相同安全要求的逻辑资产或物理资产的集合。
* 安全资源池（Security Resource Pool）
安全资源池是云计算平台中提供安全服务的资源的集合。
* 边缘计算（Edge Computing）
边缘计算是指在靠近物或数据源头的一侧，采用网络、计算、存储、应用核心能力为一体的开放平台，就近提供最近端服务。其应用程序在边缘侧发起，产生更快的网络服务响应，满足行业在实时业务、应用智能、安全与隐私保护等方面的基本需求。
* 边缘节点（Edge Node）
边缘节点是对边缘网关、边缘控制器、边缘服务器等边缘侧多种产品形态的基础共性能力的逻辑抽象，这些产品形态具备边缘侧实时数据分析、本地数据存储、实时网络联接等共性能力。
* 边缘控制器（Edge Controller）
边缘控制器是位于 IT 和 OT 之间的一个物理接口，在完成工作站或生产线的控制功能基础上，提升工业设备的接口能力和计算能力，提高工业设备的适用性。
* 边缘网关（Edge Gateway）
边缘网关是部署在网络边缘侧的网关，通过网络联接、协议转换等功能联接物理和数字世界，提供轻量化的联接管理、实时数据分析及应用管理功能。
* 边缘云（Edge Cloud）
边缘云是分布在网络边缘侧，提供实时数处理、分析决策的小规模云数据中心。
* 边缘智能（Edge Intelligence）
边缘智能指边缘节点在边缘侧提供的高级数据分析、场景感知、实时决策、自组织与协同等服务。
* 边云协同（Edge-Cloud Coordination）
边云协同指的是边缘计算多数部署和应用场景需要边缘侧与中心云的协同，包括资源协同、应用协同、数据协同、智能协同等多种协同。
* 标识编码（Identifier）
标识编码指能够唯一识别机器、产品等物理资源和算法、工序等虚拟资源的身份符号。
* 标识解析二级节点（Second-Level Node of Identification and Resolution）
标识解析二级节点指一个行业或者区域内部的标识解析公共服务节点，能够面向行业或区域提供标识编码注册和标识解析服务，以及完成相关的标识业务管理、标识应用对接等。
* 标识解析递归解析节点（Recursive Node of Identification and Resolution）
标识解析递归解析节点指标识解析体系的关键性入口设施，能够通过缓存等技术手段提升整体服务性能。
* 标识解析国家顶级节点（National Top-Level Node of Identification and Resolution）
标识解析国家顶级节点指一个国家或者地区内部最顶级的标识解析服务节点，能够面向全国范围提供顶级标识编码注册和标识解析服务，以及标识备案、标识认证等管理能力。国家顶级节点既要与各种标识体系的国际根节点保持连通，又要连通国内的各种二级及以下其他标识解析服务节点。
* 标识解析国际根节点（Root Node of Identification and Resolution）
标识解析国际根节点指某一种标识体系管理的最高层级服务节点，不限于特定国家或者地区，而是面向全球范围提供公共的根区数据管理和根解析服务。
* 标识解析企业节点（Enterprise Node of Identification and Resolution）
标识解析企业节点指一个企业内部的标识解析服务节点，能够面向特定企业提供标识编码注册和标识解析服务。既可以独立部署，也可以作为企业信息系统的组成要素。
* 不可否认性（Non-repudiation）
不可否认性是指防止服务发送方或服务接收方抵赖所接收、传输、处理、分发和共享的信息，要求无论发送方还是接收方都不能抵赖所进行的数据传输、数据处理和数据存储行为。
* 残余风险（Residual Risk）
 残余风险是指采取了安全措施后，信息系统仍然可能存在的风险。
* 产品全生命周期管理 (Product Lifecycle Management, PLM)
产品全生命周期管理是指管理产品从需求、规划、设计、生产、经销、运行、使用、维修保养、直到回收再用处置的全生命周期中的信息与过程。它既是一门技术, 又是一种制造的理念。它支持并行设计、敏捷制造、协同设计和制造, 网络化制造等先进的设计制造技术。
* 产品谱系追溯 (Product Pedigree Traceability)
产品谱系追溯是指采集整合原材料、在制品和产品服务/维护数据，基于统一编码标识实现完整的可追溯的产品谱系。
* 产品追溯编码技术 (Product Traceability Coding Technology)
产品追溯编码技术是对可溯源产品的编码格式进行数据结构定义、分配及管理的技术。编码的分配主体及数据结构是由编码命名体系本身的适用范围决定的。
* 产品追溯发现技术 (Product Traceability Discovery Technology)
产品追溯发现技术是产品实现全生命周期追溯的典型应用场景的核心。一个商品从制造到出现在消费者手里，需要经历生产、加工、物流、销售等多个环节，每个环节该商品标识都会留下信息，而每个环节都由不同管理主体管理。标识发现技术就是找到该商品标识留下信息的所有环节对应的标识，例如每个环节的信息服务器 IP 地址，这些信息服务器会记录该商品标识在本环节产生的相关信息。
* 产品追溯载体技术 (Product Traceability Carrier Technology)
产品追溯载体技术是承载方式及载体选择技术，包括一维条码、二维条码、RFID 标签、传感器等。
* 脆弱性态势（Vulnerability Situation）
 脆弱性态势是对工业设备系统安全配置的脆弱性进行识别、分析，并指出工业互联网资产存在的安全配置的脆弱性，展示漏洞总体分布、存在高危漏洞的资产、漏洞类型分布、漏洞危害等级等态势。
* 大数据安全保障（Big Data Security Assurance）
大数据安全保障对大数据基础设施、数据资产和应用服务进行安全保障的一系列适当行为或过程。
* 大数据安全参考框架（Reference Framework of Big Data Security）
大数据安全参考框架是指基于系统科学构建的从保障目标、保障对象、保障措施维度对大数据系统进行全方位安全保障的概念模型。
* 大数据服务（Big Data Service）
大数据服务是指通过底层可伸缩的大数据平台和上层各种大数据应用，支撑机构或个人对海量、异构、快速变化数据采集、传输、存储、处理（包括计算、分析、可视化等）、交换、销毁等覆盖数据生命周期相关活动的各种数据服务。
* 对象标识符 (Object Identifier, OID)
对象标识符是与对象相关联的用来无歧义地标识对象的全局唯一的值，可保证对象在通信或信息处理中正确地定位和管理。
* 分布式控制系统（Distributed Control System, DCS）
分布式控制系统以计算机为基础，在系统内部（单位内部）对生产过程进行分布控制、集中管理的系统。
* 根区文件(Root Zone File)
根区文件是指存储标识解析体系中最高层级映射的信息数据文件。
* 根服务节点(Root Node)
根服务节点是标识解析体中最高层级的节点，限于特定国家或者地区，而是面向全球范围提供公共的根区数据管理和根解析服务。
* 工控安全事件（Industrial Control Security Incident）
工控安全事件是指由于人为、软硬件缺陷或故障、自然灾害等原因，对工业控制系统、工业控制系统数据造成或者可能造成严重危害，影响正常工业生产的事件。
* 工业防火墙 (Industrial Firewall)
工业防火墙是一个有软件和硬件设备组合而成、在内部网和外部网之间、专用网与公共网之间的边界上构造的保护屏障。
* 工业 APP 开发平台(Development Platform for Industrial Applications )
工业 APP 开发平台是支持工业 APP 开发的平台，按照工业 APP 的类型不同，可细分为研发设计类、生产制造类、运营维护类、经营管理类、通用支撑类工业 APP 开发平台。
* 工业 APP 运营平台（Operating Platform for Industrial Applications）
工业 APP 运营平台是支持工业 APP 运营的平台，是工业应用企业与工业 APP 开发者之间的纽带。
* 基础设施即服务(Infrastructure as a Service，IaaS）
基础设施即服务指用户通过 Internet 可以从完善的计算机基础设施获得服务，主要提供了虚拟计算、存储、数据库等基础设施服务，通常分为三种用法：公有云、私有云和混合云。其中公有云通常指第三方提供商为多个用户提供的能够使用的云；私有云是为一个客户单独使用而构建的，因而提供对数据、安全性和服务质量的最有效控制；混合云是公有云和私有云两种服务方式的结合。
* 机理模型（Mechanism Model）
机理模型，亦称白箱模型。根据对象、生产过程的内部机制或者物质流的传递机理建立起来的精确数学模型。它是基于质量平衡方程、能量平衡方程、动量平衡方程、相平衡方程以及某些物性方程、化学反应定律、电路基本定律等而获得对象或过程的数学模型，机理模型的优点是参数具有非常明确的物理意义。在工业互联网平台上，核心问题是如何将机理模型引入到数据模型或者将数据模型输入到机理模型。
* 工业软件（Industrial Software）
工业软件是用于或专用于工业领域，为提高工业研发设计、业务管理、生产调度和过程控制水平的相关软件和系统。
* 工业数据空间（Industrial Data Space）
工业数据空间指数据提供者和数据使用者之间进行数据交换的通用模式。
* 工业大数据管理平台（Industrial Big Data Management Platform）
工业大数据管理平台是面向工业 APP 开发及应用、工业产品的开发与管理、工业企业生产经营管理等业务体系，全面支持工业应用大数据的创建、管理、分发和应用的数据管理平台。
* 工业以太网（Industrial Ethernet）
工业以太网是在工业环境的自动化控制及过程控制中应用以太网的相关组件及技术。工业以太网会采用 TCP/IP 协议，和 IEEE 802.3 标准兼容，但在应用层会加入各自特有的协议。
* 供应链金融（Supply Chain Finance）
供应链金融是指银行围绕供应链中的核心企业，管理上下游中小企业的资金流和物流，并把单个企业的不可控风险转变为供应链企业整体的可控风险，通过全方位多渠道获取企业的各类信息，将风险控制在最低的金融服务。
* 骨干网络 (Backbone Network)
骨干网络是属于具有分布式网状拓扑结构的分组交换网络。信息以分组的形式通过由到达同一目的地的多个路径构成的网络传送。网络通过路由器(它按照分组的目的地路径将信息转发)相连。“网状拓扑结构”提供了冗余链路。如果某个链路出现故障,分组会避开此链路按其他路径选择路由。
* 故障预测 (Fault Prediction)
故障预测是指基于存储在大数据存储与分析平台中的数据，通过设备使用数据、工况数据、主机及配件性能数据、配件更换数据等设备与服务数据，进行设备故障、服务、配件需求的预测，为主动服务提供技术支撑，延长设备使用寿命，降低故障率。
* 关联分析 (Association Analysis)
关联分析又称关联挖掘，就是在交易数据、关系数据或其他信息载体中，查找存在于项目集合或对象集合之间的频繁模式、关联、相关性或因果结构。
* 关系型数据库 (Relational Database)
关系数据库，是建立在关系模型基础上的数据库，借助于集合代数等数学概念和方法来处理数据库中的数据。关系模型由关系数据结构、关系操作集合、关系完整性约束三部分组成。
* 互操作 (Interoperability)
指两个或多个系统之间交换信息，能够相互理解信息的含义，并在操作上能够相互协同。
* 混合现实（Mixed Reality, MR）
混合现实（MR）技术是虚拟现实技术的进一步发展，该技术通过在虚拟环境中引入现实场景信息，在虚拟世界、现实世界和用户之间搭起一个交互反馈的信息回路，以增强用户体验的真实感。
* 基于模型的企业 (Model Based Enterprise, MBE)
基于模型的企业是采用建模与仿真技术对设计、制造、产品支持的全部技术的和业务的流程进行彻底的改进、无缝的集成以及战略的管理，利用产品和过程模型来定义、执行、控制和管理企业的全部过程。
* 基于模型的设计 (Model Based Definition, MBD)
基于模型的设计是用集成的三维实体模型来表达完整产品定义信息的方法体，它在三维实体模型上附加了产品的尺寸、公差信息，是一种更便于用户 理解且更具效率的产品信息定义方法。
* 机器学习（Machine Learning）
机器学习是一门人工智能的科学，主要研究对象是人工智能，特别是如何在经验学习中改善具体算法的性能。
* 加密（Encipherment/Encryption）
一种基于密码算法对数据的可逆变换，用于隐藏数据的信息。
* 交叉验证 (Cross-validation)
交叉验证主要用于建模应用中，例如 PCR、PLS 回归建模中，指的是在给定的建模样本中，拿出大部分样本进行建模型，留小部分样本用刚建立的模型进行预报，并求这小部分样本的预报误差，记录它们的平方加和。
* 解析系统（Resolution System）
解析系统指能够根据标识编码查询目标对象网络位置或者相关信息的系统装置，对机器和物品进行唯一性的定位和信息查询，是实现全球供应链系统和企业生产系统的精准对接、产品全生命周期管理和智能化服务的前提和基础。
* 开源框架（Open Source Framework）
开源框架是定义开源软件实现的一组功能集或工具、接口依赖关系及实现逻辑。
* 开源软件（Open Source Software）
开源软件是按一定规则和协议实现源代码对开发者开放的软件。
* 开源社区（Open Source Community）
开源社区是为开源软件开发者搭建的开发、使用、交流开源软件和技术的网络平台。
* 可编程逻辑控制器（Programmable Logic Controller, PLC）
可编程逻辑控制器是专为工业生产设计的一种数字运算操作的电子装置，它采用一类可编程的存储器，用于其内部存储程序，执行逻辑运算，顺序控制，定时，计数与算术操作等面向用户的指令，并通过数字或模拟式输入/输出控制各种类型的机械或生产过程。是工业控制的核心部分。
* 控制设备（Control Equipment）
控制设备是工业生产过程中用于控制执行器以及采集传感器数据的装置，包括分布式控制系统（DCS）的现场控制单元、可编程逻辑控制器（PLC）以及远程终端单元（RTU）等进行生产过程控制的单元设备。
* 离散制造（Intermittent/Discrete Manufacturing）
离散制造是指产品的生产过程通常被分解成很多加工任务来完成，每项任务仅要求企业的一小部分能力和资源。
* 面向工业过程自动化的工业无线网络(Wireless Networks for Industrial Automation Process Automation, WIA-PA)
面向工业过程自动化的工业无线网络是中国工业无线联盟针对过程自动化领域制定的 WIA 子标准，是基于 IEEE 802.15.4 标准的用于工业过程测量、监视与控制的无线网络系统。
* 内存数据库 (Memory Database)
内存数据库基于全部数据都在内存中重新设计的数据存储架构，与磁盘数据管理相比，内存数据库在数据缓存、快速算法、并行操作方面也进行了相应的改进，所以数据处理速度比传统数据库的数据处理速度要快很多，一般都在 10 倍以上。内存数据库的最大特点是其“主拷贝”或“工作版本”常驻内存，即活动事务只与实时内存数据库的内存拷贝打交道。
* 区块链 (Blockchain)
区块链是分布式数据存储、点对点传输、共识机制、加密算法等计算机技术的新型应用模式。区块链技术是利用块链式数据结构来验证与存储数据、利用分布式节点共识算法来生成和更新数据、利用密码学的方式保证数据传输和访问的安全、利用由自动化脚本代码组成的智能合约来编程和操作数据的一种全新的分布式基础架构与计算方式。
* 确定性网络（Deterministic Networking）
确定性网络指在一个网络域内给承载的业务提供确定性业务保证的能力，这些确定性业务保证能力包括时延，时延抖动，丢包率等指标。
* 人工智能 (Artificial Intelligence)
人工智能是研究、开发用于模拟、延伸和扩展人的智能的理论、方法、技术及应用系统的一门新的技术科学。
* 柔性制造 (Flexible Manufacturing)
柔性制造可以表述为两个方面：一个方面是指生产能力的柔性反应能力，也就是机器设备的小批量生产能力；第二个方面，指的是供应链的敏捷和精准的反应能力。这种以消费者为导向的，以需定产的方式对立的是传统大规模量产的生产模式。
* 软件定义网络 (Software Defined Networking, SDN)
软件定义网络是一种新型的网络架构，它将网络控制平面和转发平面分离， 采用集中控制替代原有分布式控制，并通过开放和可编程接口实现软件定义。
* 射频识别 (Radio Frequency Identification, RFID)
射频识别是一种通信技术，可通过无线电讯号识别特定目标并读写相关数据，而无需识别系统与特定目标之间建立机械或光学接触。
* 射频识别定位技术 (RFID Location Technology)
RFID 定位技术是采用射频识别技术，通过 RFID 信号识别终端的定位技术。该定位由阅读器获取终端数据，采用 RSSI 或者 TDOA 计算方法，实现终端位置的计算。
* 深度学习（Deep Learning）
深度学习是机器学习的分支，是一种以人工神经网路为架构，对资料进行表征学习的算法。深度学习是机器学习中一种基于对数据进行表征学习的算法。观测值可以使用多种方式来表示，如每个像素强度值的向量，或者更抽象地表示成一系列边、特定形状的区域等。而使用某些特定的表示方法更容易从实例中学习任务。深度学习的好处是用非监督式或半监督式的特征学习和分层特征提取高效算法来替代手工获取特征。
* 身份鉴别（Entity Authentication）
身份鉴别指鉴别一个实体拥有其声明的身份。
* 时间敏感网络 (Time-Sensitive Network, TSN)
时间敏感网络是一种具有有界传输时延、低传输抖动和极低数据丢失率的高质量实时传输网络。它基于标准以太网，凭借时间同步、数据调度、负载整形等多种优化机制，来保证对时间敏感数据的实时、高效、稳定、安全传输。
* 时间序列数据库 (Temporal Database)
时间序列数据库主要用于指处理带时间标签（按照时间的顺序变化，即时间序列化）的数据，带时间标签的数据也称为时间序列数据。基于时间序列数据的特点，关系型数据库无法满足对时间序列数据的有效存储与处理，因此迫切需要一种专门针对时间序列数据来做优化的数据库系统，即时间序列数据库。
* 数据安全（Data Security）
数据安全指以数据为中心的安全，保护数据的可用性、完整性和机密性。
* 数据服务（Data Service）
数据服务指提供数据采集、数据传输、数据存储、数据处理（包括计算、分析、可视化等）、数据交换、数据销毁等数据各种生存形态演变的一种信息技术驱动的服务。
* 数据管理（Data Management）
数据管理是利用计算机硬件和软件技术对数据进行有效的收集、存储、处理和应用的过程，其目的在于充分有效地发挥数据的作用。在工业互联网平台领域，数据管理主要指提供面向工业场景的对象存储、关系数据库、NoSQL 数据库等数据管理和存储的工具。
* 数据流通 (Data Flow)
数据流通可以定义为某些信息系统中存储的数据作为流通对象，按照一定的规则从供应方传递到需求方的过程。
* 数据脱敏 （Data Desensitization）
数据脱敏指对敏感信息进行数据变形处理，实现对敏感隐私信息的保护。
* 数据挖掘（Data Mining）
数据挖掘一般是指从大量的数据中通过算法搜索隐藏于其中信息的过程。数据挖掘通常与计算机科学有关，并通过统计、在线分析处理、情报检索、机器学习、专家系统（依靠过去的经验法则）和模式识别等诸多方法来实现上述目标。
* 数据血缘关系（Data Lineage）
数据血缘关系是指数据在产生、处理、流转到消亡过程中，数据之间形成的一种类似于人类社会血缘关系的关系。
* 数据预处理 (Data Preprocessing)
数据预处理指对原始数据的过滤、清洗、聚合、质量优化（剔除坏数据等）和语义解析。
* 数据资产 (Data Asset)
数据资产是指由企业拥有或者控制的，能够为企业带来未来经济利益的，以物理或电子的方式记录的数据资源，如文件资料、电子数据等。在企业中，并非所有的数据都构成数据资产，数据资产是能够为企业产生价值的数据资源。
* 数据资产管理 (Data Asset Management)
数据资产管理指规划、控制和提供数据及信息资产的一组业务职能，包括开发、执行和监督有关数据的计划、政策、方案、项目、流程、方法和程序，从而控制、保护、交付和提高数据资产的价值。数据资产管理是需要充分融合业务、技术和管理，来确保数据资产保值增值。
* 数据治理 (Data Governance)
数据治理指对数据资产管理活动行使权力和控制的活动集合（规划、监控和执行）。数据治理职能指导其他数据管理职能如何执行。数据治理制定正确的原则、政策、流程、操作规程，确保以正确的方式对数据和信息进行管理。
* 数字化双胞胎 (Digital Twins)
数字化双胞胎是指以数字化方式拷贝一个物理对象，模拟对象在现实环境中的行为，对产品、制造过程乃至整个工厂进行虚拟仿真，从而提高制造企业产品研发、制造的生产效率。
* 态势感知（Situation Awareness）
态势感知指认知一定时间和空间内的环境要素，理解其意义，并预测它们即将呈现的状态，以实现决策优势。
* 网络安全漏洞（Cybersecurity Vulnerability）
网络安全漏洞是网络系统在需求、设计、实现、配置、运行等过程中，无意或有意产生的缺陷或薄弱点。这些缺陷或薄弱点以不同形式存在于网络系统的各个层次和环节之中，一旦被恶意主体所利用，就会对网络系统的安全造成损害，从而影响网络系统的正常运行。
* 网络边界（Network Boundary）
网络边界是工业互联网的安全计算环境边界，以及安全计算环境与安全通信网络之间实现连接并实施安全策略的相关部件。
* 网络虚拟化 (Network Virtualization)
网络虚拟化是能够实现网络资源动态调配、动态管理的技术。
* 威胁情报（Threat Intelligence）
威胁情报是一种基于证据的知识，包含了上下文、机制、指示标记、启示和可行的建议。威胁情报描述了现存的或者是即将出现针对资产的威胁或危险，并可以用于通知主体针对相关威胁或危险采取某种响应。
* 物联网 (Internet of Things, IoT)
物联网是通信网和互联网的拓展应用和网络延伸，它利用感知技术与智能装臵对物理世界进行感知识别，通过网络传输互联，进行计算、处理和知识挖掘，实现人与物、物与物信息交互和无缝链接，达到对物理世界实时控制、精确管理和科学决策目的。
* 无线局域网（Wireless Local Area Network, WLAN）
无线局域网是不使用任何导线或传输线缆连接的局域网，而使用无线电波作为数据传送的介质，传送范围一般在局部区域。无线局域网用户通过一个或多个无线收发器接入无线局域网。目前无线局域网最通用的标准是 IEEE 定义的 802.11 系列标准。
* 无源光网络（Passive Optical Network, PON）
无源光网络包括一个安装于中心控制站的光线路终端（OLT），以及一批配套的安装于用户场所的光网络单元（ONUs）；在 OLT 与 ONU 之间的光配线网（ODN）全部由光分路器等无源器件组成，不需要有源电子设备。
* 现场级 (Work Cell)
现场级由企业确定的一个物质的、地理的或逻辑的生产群组，完成的某项工序活动。
* 现场总线 (Field Bus)
现场总线是连接智能现场设备和自动化系统的数字式、双向传输、多分支结构的通信网络。
* 协同设计 (Collaborative Design)
协同设计是企业与企业之间,通过网络化的设计平台,分工并行开展的产品设计模式,可有效缩短产品设计周期。
* 协同制造 (Collaborative Manufacturing)
协同制造指基于网络协同平台，将制造任务、订单信息分配给不同地域、不同规模的制造企业，将社会分散的制造资源、制造能力在网络平台进行集聚共享，形成网络化协同的生产组织模式。
* 信息安全保障能力（Capability of Information Security Assurance）
信息安全保障能力是被保障实体安全防御、响应和恢复等特性的体现。
* 信息安全风险（Information Security Risk）
信息安全风险指人为或自然的威胁利用系统及其管理体系中存在的脆弱性导致安全事件的发生及其对组织造成的影响。
* 信息安全事件（Security Incident）
信息安全事件是由单个或一系列意外或有害的信息安全事态所组成的，极有可能危害业务运行或威胁信息安全。
* 信息保障技术框架 (Information Assurance Technical Framework, IATF)
信息保障技术框架由美国国家安全局于 1998 年提出，该框架提出保障信息系统安全应具备的三个核心要素，即人、技术和操作。其中，人这一要素包括保障人身安全、对人员进行培训、制定安全管理制度等，强调了人作为防护措施的具体实施者在安全防护中的重要地位。
* 消息队列遥测传输（Message Queuing Telemetry Transport, MQTT）
消息队列遥测传输是 ISO 标准(ISO/IEC PRF 20922)下基于发布/订阅范式的消息协议。它工作在 TCP/IP 协议族上，是为硬件性能低下的远程设备以及网络状况糟糕的情况下而设计的发布/订阅型消息协议。
* 信息模型 (Information Model)
信息模型是对数据的语义提供概念、关系、约束、操作的模型化表示，实现 信息的可共享、可组织。
* 信息物理系统 (Cyber-Physical Systems, CPS)
信息物理系统是一个综合计算、网络和物理环境的多维复杂系统，通过 3C（Computer、Communication、Control）技术的有机融合与深度协作，实现大型工程系统的实时感知、动态控制和信息服务。CPS 实现计算、通信与物理系统的一体化设计，可使系统更加可靠、高效、实时协同，具有重要而广泛的应用前景。
* 行为态势（Behavior Situation）
行为态势指通过工业网络流量分析工业互联网用户行为和设备行为，及时发现工业互联网用户和设备的异常状态，并进行态势分析。
* 许可证（License）
许可证是就某一产品特定功能、容量、使用期限等方面进行授权的许可。许可可以是文件或序列号的形式。许可通常由加密密码组成，操作权限随许可的级别而不同。
* 虚拟仿真 (Virtual Reality)
虚拟仿真是用一个系统模仿另一个真实系统的技术。虚拟仿真实际上是一种可创建和体验虚拟世界的计算机系统。此种虚拟世界由计算机生成，可以是现实世界的再现，亦可以是构想中的世界，用户可借助视觉、听觉及触觉等多种传感通道与虚拟世界进行自然的交互。
* 业务 Fabric (Business Fabric)
业务 Fabric 是模型化的工作流，由多种类型的功能服务按照一定逻辑关系组成和协作，实现特定的业务 需求，是对业务需求的数字化表示。服务的模型，包括服务名称、执行或提供什么样的功能，服务间的嵌套、依赖、继承等关系，每个服务 的输入与输出，以及 Qos、安全、可靠性等服务约束。服务的类型不仅包括边缘计算提供的通用服务，还包括垂直行业所定义的特定行业服务。
* 异构计算 (Heterogeneous Computing)
异构计算目标是整合同一个平台上分立的处理单元使之成为紧密协同的整体来协同处理不同类型的计算负荷。同时通过开放统一的编程接口，实现软件跨多种平台。协同和发挥各种计算单元的独特优势。
* 异构识别技术 (Heterogeneous Recognition Technology)
异构识别技术针对产品追溯编码不一致，全生命周期“一物多码”的现状，分析出当前产品追溯异构标识的编码规律及趋势，针对产品追溯异构标识识别的冲突问题，提出适用于现有工业互联网领域产品追溯异构标识识别的冲突检测模型及判定算法，为未来新的工业互联网异构标识编码制定提供防冲突策略，并针对已冲突异构标识设计后向兼容机制，最大程度解决产品追溯异构标识识别中的冲突问题。
* 以太网控制自动化技术(Ethernet Control Automation Technology，EtherCAT)
以太网控制自动化技术是一个开放架构，以以太网为基础的现场总线系统。EtherCAT 是确定性的工业以太网，最早是由德国的 Beckhoff 公司研发。
* 元数据 (Metadata)
元数据是描述数据的数据。元数据按用途不同分为技术元数据、业务数据和管理元数据。
* 云安全服务（Cloud Security Service）
云安全服务指用于保护云计算基础设施及其上业务系统和数据的信息安全服务。
* 云安全服务商（Cloud Security Service Provider）
云安全服务商指提供云安全服务的供应方。
* 云存储基础设施（Cloud Storage Infrastructure）
云存储基础设施是满足云存储模式需求的硬件和软件部分，例如服务器、存储、虚拟化软件及操作系统。云存储基础设施与传统的数据存储基础设施有所不同，因为它远程地通过网络访问文件，且通常内置于基于对象的存储平台。企业迁移到云存储将需要基础设施确保多租户、自主计算、存储效率、扩展性、效用计算以及集成数据保护。
* 云计算（Cloud Computing）
云计算通过互联网，“按使用量付费”的方式提供随需应变的计算资源（从应用到数据中心）。其部署方式包括公有云、私有云和混合云。云计算通常简称为“云”。
* 云制造（Cloud Manufacturing）
云制造是一种基于泛在网络，借助新兴制造技术、新兴信息技术、智能科学技术及制造应用领域技术等 4 类技术深度融合的数字化、网络化、智能化技术工具，构成以用户为中心的制造资源、产品与能力的服务云（网），使用户通过智能终端及制造云服务平台便能随时随地按需获取制造资源、产品与能力服务, 对制造全系统、全生命周期活动（产业链）中的人、机、物、环境、信息进行自主智能地感知、互联、协同、学习、分析、认知、决策、控制与执行，促使制造全系统及全生命周期活动中的人/组织、技术/设备、管理、数据、材料、资金（六要素）及人流、技术流、管理流、数据流、物流、资金流（六流）集成优化；形成一种用户为中心的互联化（协同化）、服务化、个性化（定制化）、柔性化、社会化、智能化的制造新模式。
* 云制造产业集群（Cloud Manufacturing Industry Cluster）
云制造产业集群是指区别于传统线下产业集群内各主体的生产协作方式，以工业互联网和新一代信息技术为手段，通过某工业云或工业互联网平台聚集某一行业内的竞争性企业以及与这些企业互动关联的合作企业、专业化供应商、服务供应商、相关产业厂商和相关机构(如大学、科研机构、制定标准的机构、产业公会等），并通过云端开展线上生产服务协同协作的新型产业空间组织形式。
* 责任制（Accountability）
责任制是运营工业互联网业务的企业内部各个部门及其供应链相关组织、各类人员的工作范围、应负责任及相应权力的制度。
* 增强机器类通信 (Enhanced Machine Type Communication, eMTC)
增强机器类通信是万物互联技术的一个重要分支，基于 LTE 协议演进而来，为了更加适合物与物之间的通信，也为了更低的成本，对 LTE 协议进行了裁剪和优化 eMTC 基于蜂窝网络进行部署，其用户设备通过支 1.4MHz 的射频和基带带宽，可以直接接入现有的 LTE 网络。eMTC 支持上下行最大 1Mbps 的峰值速率，可以支持丰富、创新的物联应用。
* 增强现实（Augmented Reality，AR）
增强现实是通过将三维内容投射到某介质上，呈现真实的人、场景与虚拟物体结合效果，与虚拟现实最大的不同是其中多了现实世界的东西，现实与虚拟融合。
* 窄带物联网（Narrow Band-Internet of Things, NB-IoT）
窄带物联网是基于 E-UTRAN 技术，使用 180kHz 的载波传输带宽，支持低功耗设备在广域网的一种蜂窝数据连接技术。具备广覆盖，支持海量连接，支持低时延敏感、低功率的特点。
* 智能服务（Smart Service）
智能服务是指基于模型驱动的统一服务框架，面向系统运维人员、业务决策者、系统集成商、应用开发人员等多种角色，提供开发服务框架和部署运营服务框架。
* 智能工厂（Intelligent Factory)
智能工厂是在数字化工厂的基础上，利用物联网、大数据、人工智能等新一代信息技术加强信息管理以及合理计划排程，同时集智能手段和智能系统等新兴技术于一体，构建高效、和服务，提高生产过程可控性、减少生产线人工干预，节能、绿色、环保、舒适的人性化工厂。
* 智能故障诊断 (Intelligent Fault Diagnosis)
智能故障诊断对设备运行数据进行实时采集与处理分析，根据已设定的规则进行非法操作报警、设备异常报警、偏离预定位置报警等实时报警，以及故障远程诊断、维护，并相应与智能服务平台一键智能派工服务集成。
* 智能网关（Smart Gateway）
智能网关是通过网络联接、协议转换等功能联接物理和数字世界，提供轻量化的联接管理、实时数据分析及应用管理功能的网关。
* 智能系统（Smart System）
智能系统是基于多个分布式智能网关、服务器的协同构成智能系统，提供弹性扩展的网络、计算、存储能力。
* 智能资产（Smart Asset）
智能资产指通过融合网络、计算、存储等 ICT 能力，具有自主化和协作化能力的资产（物）。
* 知识模型（Knowledge Model）
知识模型是将知识进行形式化和结构化的抽象，主要解决知识的表示、组织与交互关系，知识的有序化以及知识处理模型。知识模型不是知识，是知识的抽象，以便于计算机理解与处理。
* 知识图谱（Knowledge Graph）
知识图谱是描述真实世界中存在的各种实体、概念及其关系构成的语义网络，现在泛指各种大规模知识库。
* 知识自动化 (Knowledge Automation)
知识自动化是一种可执行知识工作任务的智能软件系统。它除了包含传统的规则、推理和显性表达式之外，也对隐含知识、模式识别、群体经验等进行模型化，并借助软件化的方式，形成可执行的知识软件系统。这将大大解放知识工作者的重复性劳动。
* 专家系统（Expert System）
专家系统是人工智能早期的一个重要分支，是一类具有专门知识和经验的计算机智能程序系统。
* 资产态势（Asset Situation）
资产态势是指利用工业互联网设备特征库，识别接入的各种类型的工业互联网资产的型号、版本、运行状态等，获取工业互联网资产总数，并按区域、类型、重要程度分布等进行统计分析，实时呈现工业互联网资产的拓扑结构和分布态势。
* 设备接入（Device Access）
设备接入主要基于工业以太网、工业总线等工业通信协议，以太网、光纤等通用协议，3G/4G、NB-IOT 等无线协议将工业现场设备接入到平台边缘层，又叫“设备联网”， 是建立物理世界和数字世界的联接的起点，是数字化信息的源头。培育工业互联网平台，第一步就是将工厂中的所有设备联网，这是最基本的先决条件。
附件（各组反馈，但不准备纳入的术语定义）
* 工业物联网（Industrial Internet of Things, IIoT）
将具有感知、监控能力的各类采集或控制传感或控制器以及泛在技术、移动通信、智能分析等技术不断融入到工业生产过程各个环节，从而大幅提高制造效率，改善产品质量，降低产品成本和资源消耗，最终实现将传统工业提升到智能化的新阶段。
* 工业物联网数据（Industrial Internet of Things Data）
在工业应用中，由生产设备或者智能装备的传感器所产生的海量时序数据。
* 智能制造（Intelligent Manufacturing）
智能制造应当包含智能制造技术和智能制造系统，智能制造系统不仅能够在实践中不断地充实知识库，而且还具有自学习功能，还有搜集与理解环境信息和自身的信息，并进行分析判断和规划自身行为的能力。
* 信息通信技术 (Institute of Computing Technology, ICT)
ICT 是信息、通信和技术三个英文单词的词头组合(Information Communications Technology，简称 ICT)。它是信息技术与通信技术相融合而形成的一个新的概念和新的技术领域。
* 人力资源管理系统 (Human Resources System, HCM)
通过提高内部员工的满意度、忠诚度，从而提高员工贡献度，即绩效，帮助管理者通过有效组织管理降低成本和加速增长来创造价值链利润。人力资源综合管理解决方案从人力资源管理的角度出发，用集中的数据将几乎所有与人力资源相关的信息统一管理起来。
* 工业互联网产业联盟(Alliance of Industrial Internet,  AII)
工业互联网产业联盟接受工业和信息化部业务指导，中国信息通信研究院是联盟理事长单位。联盟还包括航天科工、中国电信、海尔、华为等 9 家副理事长单位。
* 美国工业互联网联盟 (Industrial Internet Consortium, IIC)
由 AT&T、思科(Cisco)、通用电气(GE)、IBM 和英特尔(intel)在美国波士顿成立工业互联网联盟(IIC)，以期打破技术壁垒，通过促进物理世界和数字世界的融合。
* Hadoop 分布式文件系统（Hadoop Distributed File System，HDFS）
Hadoop 的核心框架，为海量的数据提供存储，具有高容错性、高吞吐量等特点，适合有着超大数据集（large data set）的应用程序。
* IPv6
Internet Protocol Version 6 的缩写，即互联网协议版本 6，是互联网协议的一个新版本。
* 安全相关要求（Security Related Requirement）
直接影响系统安全运行或者强制执行规定安全策略的要求。
* 安全需求 （Security Requirement）
为保证组织业务战略的正常运作而在安全措施方面提出的要求。
* 标准必要专利（Standard-Essential Patent）
指包含在国际标准、国家标准和行业标准中，且在实施标准时必须使用的专利，也就是说当标准化组织在制定某些标准时，部分或全部标准草案由于技术上或者商业上没有其他可替代方案，无可避免要涉及到专利或专利申请。当这样的标准草案成为正式标准后，实施该标准时必然要涉及到其中含有的专利技术。
* 部署视图 (Deployment View)
阐述系统的部署过程和典型的部署场景。同时，架构需要满足跨行业的典型非功能性需求，包括实时性、确定性、可靠性等。为此，在功能视图、部署视图给出了相关技术方案推荐。
* 产品优化创新 (Product Optimization and Innovation)
对制造过程的生产数据和服务/维护过程的产品数据进行采集和处理，然后反馈到产品设计过程中，在产品设计阶段优化产品性能、创新产品功能。
* 电气和电子工程师协会 (Institute of Electrical and Electronics Engineers, IEEE)
电气和电子工程师协会是一个国际性的电子技术与信息科学工程师的协会，是目前全球最大的非营利性专业技术学会，其会员人数超过 40 万人，遍布 160 多个国家。IEEE 致力于电气、电子、计算机工程和与科学有关的领域的开发和研究，在太空、计算机、电信、生物医学、电力及消费性电子产品等领域已制定了 900 多个行业标准，现已发展成为具有较大影响力的国际学术组织。
* 多入多出技术 (Multiple-Input Multiple-Output Technology)
多入多出技术是指在发射端和接收端分别使用多个发射天线和接收天线，使信号通过发射端与接收端的多个天线传送和接收，从而改善通信质量。它能充分利用空间资源，通过多个天线实现多发多收，在不增加频谱资源和天线发射功率的情况下，可以成倍的提高系统信道容量，显示出明显的优势、被视为下一代移动通信的核心技术。
* 泛在网络（Ubiquitous）
通信网、互联网、物联网高度融合，实现多网络、多行业、多应用、异构多技术的融合与协同。
* 服务快速反应 (Service Rapid Response)
通过设备的智能化，可以通过互联网获取用户的实时工况数据。当用户设备出现问题或异常时，帮助用户更快地发现问题、找到问题的原因。通过数据分析，构建基于规则或案例的故障预测系统，对用户设备状态进行预测、帮助用户更好地维护设备。
* 工程总承包（Engineering Procurement Construction, EPC）
工程总承包，是指公司受业主委托，按照合同约定对工程建设项目的设计、采购、施工、试运行等实行全过程或若干阶段的承包。通常公司在总价合同条件下，对其所承包工程的质量、安全、费用和进度进行负责。
* 功能设计视图 (Functional Design View)
阐述横向的开发服务框架、部署运营框架业务 Fabric、联接计算 Fabric 和 ECN，纵向的跨层次开放服务、 管理服务、数据全生命周期服务、安全服务的功能与设计思路。
* 场景模版工业 APP（Industrial Applications for Scene Templates）
场景模版工业 APP 对服务于企业内、外各环节业务协同的工业场景进行模板化封装后形成的工业 APP，是工业 APP 基于应用模式维度进行分类的一种工业 APP。
* 工程模型工业 APP（Industrial Applications for Engineering Models）
对服务于产品开发不同阶段的工程模型、数字样机、信息物理系统进行模型化封装后形成的工业 APP，是工业 APP 基于应用模式维度进行分类的一种工业 APP。
* 工业产品创新开发平台（Industrial Product Innovation and Development Platform）
支持工业 APP 融合化应用及工业产品创新开发的平台。相对于传统工业产品开发平台，工业产品创新开发平台基于工业互联网平台融合各类型应用系统，能够有效实现基于模型和知识的工业产品创新开发能力。
* 工业、科学和医疗应用（Industrial，Scientific and Medical Applications）
工业、能在局部范围内产生射频能量并利用这种能量为工业、科学、医疗、民用或类似领域提供服务的设备或器械的运用，但不包括电信领域内的运用。

* 行业通用工业 APP（Industrial Applications for General）
对适用于整个行业的工业知识和经验软件化后形成的工业 APP，是工业 APP 基于技术体系维度进行分类的一种工业 APP。
* 行业智能 1.0（Industry Intelligence 1.0）
行业智能 1.0 是面向市场线索、营销、采购、物流、售后等商业过程，将用户、应用和商业流程的行为和 状态数字化，基于多维度数据分析和场景感知，建立行业的信息图谱，为行业用户提供个性化的资源配置和服务。
* 行业智能 2.0（Industry Intelligence 2.0）
行业智能 2.0 面向产品规划、设计、制造、运营等生产过程，产品、生产装备、工艺流程等已经逐步数字化和网络化，行业智能 2.0 已经具备了基础条件。这里所指的产品、装备具有广义的概念，既包括制造业所生产的产品 和制造产线等，也包括能源、交通、农业、公共事业等行业提供服务时所依赖的资产，如电表、交通工具、 农业机械、环境监测仪器等。
* 混凝土预制件（Precast Concrete, PC）
在住宅工业化领域称作 PC 构件。如预制钢筋混凝土柱地基基础、预制钢结构钢柱基础、路灯广告牌柱钢筋混凝土基础、预制楼板。与之相对应的传统现浇混凝土需要工地现场制模、现场浇注和现场养护。混凝土预制件 被广泛应用于建筑、交通、水利等领域，在国民经济中扮演重要的角色。
* 基础共性工业 APP（Industrial Applications for Basic Commonality）
对结构、强度、动力、材料、化学等各行业共同需要的共性知识和经验进行软件化后形成的工业 APP，是工业 APP 基于技术体系维度进行分类的一种工业 APP。
* 建筑信息模型（Building Information Modeling，BIM）
建筑信息模型技术是一种应用于工程设计、建造、管理的数据化工具，通过对建筑的数据化、信息化模型整合，在项目策划、运行和维护的全生命周期过程中进行共享和传递，使工程技术人员对各种建筑信息作出正确理解和高效应对，为设计团队以及包括建筑、运营单位在内的各方建设主体提供协同工作的基础，在提高生产效率、节约成本和缩短工期方面发挥重要作用。
* 经营管理工业 APP（Industrial Applications for Business Management）
服务于工业企业经营管理领域的工业 APP，是工业 APP 基于产品开发维度进行分类的一种工业 APP。
* 码分多址技术 (Code Division Multiple Access, CDMA)
码分多址(CDMA)是在数字技术的分支–扩频通信技术上发展起来的一种崭新而成熟的无线通信技术。CDMA 技术的原理是基于扩频技术，即将需传送的具有一定信号带宽信息数据，用一个带宽远大于信号带宽的高速伪随机码进行调制，使原数据信号的带宽被扩展，再经载波调制并发送出去。接收端使用完全相同的伪随机码，与接收的带宽信号作相关处理，把宽带信号换成原信息数据的窄带信号即解扩，以实现信息通信。
* 频段划分（Allocation of a Frequency Band）
将某个特定的频段列入频率划分表，规定该频段可在指定的条件下供一种或多种地面或空间无线电通信业务或射电天文业务使用。
* 企业专用工业 APP（Industrial Applications Dedicated to the Enterprise）
对仅适用于工业企业内部使用的工业知识和经验软件化后形成的工业 APP，是工业 APP 基于技术体系维度进行分类的一种工业 APP。
* 生产过程优化 (Production Process Optimization)
通过分析产品质量、成本、能耗、效率、成材率等关键指标与工艺、设备参数之间的关系，优化产品设计和工艺。以实际的生产数据为基础，建立生产过程的仿真模型，优化生产流程。根据客户订单、生产线、库存、设备等数据预测市场和订单，优化库存和生产计划、排程。
* 生产制造工业 APP（Industrial Applications for Production and Manufacturing）
服务于工业产品生产制造领域的工业 APP，是工业 APP 基于产品开发维度进行分类的一种工业 APP。
* 物联网创新联盟 (Internet of Things Innovation Alliance, IOTIA)
该联盟由世界华商联盟会、世界物联网大会组委会、中国物联网发展基金筹委会、中国新媒体行业联合会等共同发起，定位于非赢利性、服务型组织。旨在让各路创业精英、创新企业、转型企业深度了解中国与全球物联网新兴经济，把握未来物联网时代的契机，推动物联网产业发展。
* 信息技术服务（Information Technology Service）
信息技术服务是指服务供方为服务需方提供如何开发和应用信息技术的服务，以及供方以信息技术为手段提供支持需方业务活动的服务。
* 研发设计工业 APP（Industrial Applications for Research and Development）
服务于工业产品研发设计领域的工业 APP，是工业 APP 基于产品开发维度进行分类的一种工业 APP。
* 运营维护工业 APP（Industrial Applications for Operational Maintenance）
服务于工业产品运营维护领域的工业 APP，是工业 APP 基于产品开发维度进行分类的一种工业 APP。
* 正交频分复用技术 (Orthogonal Frequency Division Multiplexing, OFDM)
将信道分成若干正交子信道，将高速数据信号转换成并行的低速子数据流，调制到在每个子信道上进行传输。正交信号可以通过在接收端采用相关技术来分开，这样可以减少子信道之间的相互干扰 ISI(Intersymbol Interference) 。每个子信道上的信号带宽小于信道的相关带宽，因此每个子信道上的可以看成平坦性衰落，从而可以消除符号间干扰。而且由于每个子信道的带宽仅仅是原信道带宽的一小部分，信道均衡变得相对容易。
* 智慧城市 (Smart City)
利用各种信息技术或创新意念，集成城市的组成系统和服务，以提升资源运用的效率，优化城市管理和服务，以及改善市民生活质量。智慧城市把新一代信息技术充分运用在城市的各行各业之中的基于知识社会下一代创新（创新 2.0）的城市信息化高级形态，实现信息化、工业化与城镇化深度融合，有助于缓解“大城市病”，提高城镇化质量，实现精细化和动态管理，并提升城市管理成效和改善市民生活质量。
* 智慧能源 (Smarter Energy)
智慧能源就是充分开发人类的智力和能力，通过不断技术创新和制度变革，在能源开发利用、生产消费的全过程和各环节融汇人类独有的智慧，建立和完善符合生态文明和可持续发展要求的能源技术和能源制度体系，从而呈现出的一种全新能源形式。简而言之，智慧能源就是指拥有自组织、自检查、自平衡、自优化等人类大脑功能，满足系统、安全、清洁和经济要求的能源形式。
* 智能交通系统 (Intelligent Transportation System)
智能交通系统是将先进的信息技术、数据通讯传输技术、电子传感技术、控制技术及计算机技术等有效地集成运用于整个地面交通管理系统而建立的一种在大范围内、全方位发挥作用的，实时、准确、高效的综合交通运输管理系统。
* 专利合作协定（Patent Cooperation Treaty, PCT）
专利领域的一项国际合作条约，简化在条约缔约国申请发明专利保护的方法。主要涉及专利申请的提交，检索及审查等。
* 专利优先权（Patent Priority）
包括国外优先权和本国优先权。申请人自发明或实用新型在外国第一次提出专利申请之日起规定期限内，或自外观设计在外国第一次提出专利申请之日起规定期限内，又在国内就相同主题提出专利申请的，依照该外国同本国签订的协议或者共同参加的国际条约，或者依照相互承认优先权原则，可以享有优先权。
* 装配式钢结构（Assembled building with steel-structure）
建筑的结构系统由钢（构）件构成的装配式建筑。钢结构是天然的装配式结构，但并非所有的钢结构建筑均是装配式建筑，尤其是算不上好的装配式建筑。必须是钢结构、围护系统、设备与管线系统和内装系统做到和谐统一，才能算得上是装配式钢结构建筑。
* 资源接入工业 APP（Industrial Applications for Resource Accessing）
对服务器、超性能计算、工业设备、工业产品等工业资源的服务能力进行软件化后形成的工业 APP，可独立使用或接入到工程模型工业 APP、场景模版工业 APP 中组配化使用，是工业 APP 基于应用模式维度进行分类的一种工业 APP。
* 编程语言与开发工具（Programming Language and Development Tool）
编程语言是用来定义计算机程序的形式语言，俗称“计算机语言”，种类非常的多。开发工具一些被软件工程师用于为特定的软件包、软件框架、硬件平台、操作系统等建立应用软件的特殊软件。工业互联网平台支持多类编程语言和开发工具：支持 Java、Ruby 和 PHP 等多种语言编译环境，并提供 Eclipse integration、JBoss Developer Studio、git 和 Jenkins 等各类开发工具，构建高效便捷的集成开发环境。

* 使能技术（Enabling Technology）

指应用面广、多学科交叉融合，能够在不同领域快速形成衍生技术、对用户的能力或文化产生根本性变化的发明或创新的一项或一系列技术。使能技术是从技术创新链提出的一种概念，其内涵受取决于创新目标，决定使能技术的生命力在于带动力、衍生力。工业互联网平台领域的使能技术包括云计算、大数据、人工智能等。

* 数据采集（Data Acquisition）

数据采集是利用泛在感知技术对多源设备、异构系统、运营环境、人等要素信息进行实时高效采集和云端汇聚，对应存在于工业互联网平台体系架构中的边缘层，是工业互联网平台的基础。数据采集广义范围既包括工业现场设备的数据采集和工厂外智能产品/装备的数据采集，也包括对 ERP、MES 等应用系统的数据采集。

* 协议转换（Protocol Conversion）

协议转换指将一个设备的标准或协议转换成适用于另一设备的协议的过程，目的是为了使得不同协议之间实现互操作。协议转换运用协议解析、中间件等技术兼容 ModBus、OPC、CAN、Profibus 等各类工业通信协议和软件通信接口，实现数据格式转换和统一；另一方面利用 HTTP、MQTT 等方式从边缘侧将采集到的数据传输到云端，实现数据的远程接入。
