# 工业互联网术语和定义

新增加条目格式：

- 软件定义网络（Software Defined Network, 缩略语:SDN） :: 一种网络控制和转发分离的网络架构，上层应用和服务可通过网络控制层的可编程接口实现对底层网络设备的控制。

* 总体组

- 工业互联网（Industrial Internet, II） :: 工业互联网是满足工业智能化发展需求，具有低时延、高可靠、广覆盖特点的关键网络基础设施，是新一代信息通信技术与先进制造业深度融合所形成的新兴业态与应用模式。

- 工业互联网标识解析 :: 工业互联网标识通过赋予每一个产品、零部件、机器设备唯一的“身份证”，实现全网资源的灵活区分和信息管理。工业互联网标识解析类似于互联网域名解析，可以通过产品标识查询储存产品信息的服务器地址，或者查询产品信息以及相关服务。

- 工业互联网平台 :: 指面向制造业数字化、网络化、智能化需求，构建基于海量数据采集、汇聚、分析的服务体系，支撑制造资源泛在连接、弹性供给、高效配置的工业云平台。

- 可编程逻辑控制器（Programmable Logic Controller， 缩略语：PLC） :: 专为工业生产设计的一种数字运算操作的电子装置，它采用一类可编程的存储器，用于其内部存储程序，执行逻辑运算，顺序控制，定时，计数与算术操作等面向用户的指令，并通过数字或模拟式输入/输出控制各种类型的机械或生产过程。是工业控制的核心部分。

-	知识模型	（Knowledge Model） :: 主要解决知识的表示、组织与交互关系，知识的有序化以及知识处理 模型，是将知识进行形式化和结构化的抽象。知识模型不是知识，是知识的抽象，以便于计算机理解与处理。

-	知识模型	（Knowledge Model） :: 主要解决知识的表示、组织与交互关系，知识的有序化以及知识处理 模型，是将知识进行形式化和结构化的抽象。知识模型不是知识，是知识的抽象，以便于计算机理解与处理。

-	智能资产 （Smart Asset） ::	通过融合网络、计算、存储等ICT能力，具有自主化和协作化能力的资产（物）。

-	智能网关 （Smart Gatway） ::	通过网络联接、协议转换等功能联接物理和数字世界，提供轻量化的联接管理、实时数据分析及应用管理功能的网关。

-	智能系统 （Smart System） :: 基于多个分布式智能网关、服务器的协同构成智能系统，提供弹性扩展的网络、计算、存储能力。

-	智能服务 （Smart Service） :: 基于模型驱动的统一服务框架，面向系统运维人员、业务决策者、系统集成商、应用开发人员等多种角色，提供开发服务框架和部署 运营服务框架。

-	工业大数据 （Big Industrial Data） :: 工业大数据即工业数据的总和，我们把它分成三类，即企业信息化数据、工业物联网数据，以及外部跨界数据。其中，企业信息化和工业物联网中机器产生的海量时序数据是工业数据规模变大的主要来源。 

-	行业智能1.0 （Industry Intelligence 1.0） :: 行业智能1.0是面向市场线索、营销、采购、物流、售后等商业过程，将用户、应用和商业流程的行为和 状态数字化，基于多维度数据分析和场景感知，建立行业的信息图谱，为行业用户提供个性化的资源配置和服务。

-	行业智能2.0	（Industry Intelligence 2.0） ::	行业智能2.0面向产品规划、设计、制造、运营等生产过程，产品、生产装备、工艺流程等已经逐步数字化和网络化，行业智能2.0已经具备了基础条件。这里所指的产品、装备具有广义的概念，既包括制造业所生产的产品 和制造产线等，也包括能源、交通、农业、公共事业等行业提供服务时所依赖的资产，如电表、交通工具、 农业机械、环境监测仪器等。

-	边缘计算 （Edge Computing）	::	边缘计算是指在靠近物或数据源头的一侧，采用网络、计算、存储、应用核心能力为一体的开放平台，就近提供最近端服务。其应用程序在边缘侧发起，产生更快的网络服务响应，满足行业在实时业务、应用智能、安全与隐私保护等方面的基本需求。

-	云计算	（Cloud Computing） ::	云计算通常简称为“云”。通过互联网，“按使用量付费” 的方式 提供随需应变的计算资源（从应用到数据中心）。其部署方式包括 公有云、私有云和混合云。

-	深度学习	（Deep Learning） ::	深度学习的概念源于人工神经网络的研究。含多隐层的多层感知器就是一种深度学习结构。深度学习通过组合低层特征形成更加抽象的高层表示属性类别或特征，以发现数据的分布式特征表示。

-	数据挖掘	（Data Mining） ::	 数据挖掘一般是指从大量的数据中通过算法搜索隐藏于其中信息的过程。数据挖掘通常与计算机科学有关，并通过统计、在线分析处理、情报检索、机器学习、专家系统（依靠过去的经验法则）和模式识别等诸多方法来实现上述目标。

-	智能制造	（Intelligent Manufacturing） :: 智能制造应当包含智能制造技术和智能制造系统，智能制造系统不仅能够在实践中不断地充实知识库，而且还具有自学习功能，还有搜集与理解环境信息和自身的信息，并进行分析判断和规划自身行为的能力。

* 需求组

* 技术与标准组

* 网络组

- 消息队列遥测传输（Message Queuing Telemetry Transport，缩略语：MQTT） :: ISO 标准(ISO/IEC PRF 20922)下基于发布/订阅范式的消息协议。它工作在TCP/IP协议族上，是为硬件性能低下的远程设备以及网络状况糟糕的情况下而设计的发布/订阅型消息协议。

* 工业互联网平台组

* 测试床组

* 产业发展组

* 频谱组

* 国际合作与对外交流组

* 垂直行业组

* 政策法规和投融资特设组

- 工业 APP :: 面向特定工业应用场景，开发者通过调用工业互联网云平台的资源，推动工业技术、经验、知识和最佳实践模型化、软件化、再封装而形成的应用程序。

- IPv6 :: Internet Protocol Version 6 的缩写，即互联网协议版本 6，是互联网协议的一个新版本。

- 无源光网络（Passive Optical Network, 缩略语 PON） :: 一个无源光网络包括一个安装于中心控制站的光线路终端（OLT），以及一批配套的安装于用户场所的光网络单元（ONUs）；在 OLT 与 ONU 之间的光配线网（ODN）全部由光分路器等无源器件组成，不需要有源电子设备。

- 软件定义网络（Software-Defined Networking, 缩略语:SDN） :: 一种网络控制和转发分离的网络架构，上层应用和服务可通过网络控制层的可编程接口实现对底层网络设备的控制。

- 窄带物联网（NB-IoT） :: 物联网领域的一项新兴技术，支持低功耗设备在广域网的蜂窝数据连接，也被叫作低功耗广域网。

- 时间敏感网络（Time Sensitive Network, 缩略语:TSN） :: TSN 是一种面向 1000Mbps 以及更高速率以太网接口的网络技术，它以太网技术为主体，包含了时序控制和时间同步、路径控制和预留、流量调度、帧抢占和流量预留、转发控制增强等多个局域网和城域网的桥接网络技术点。

- 边缘计算（Edge Computing） :: 边缘计算是在靠近物或数据源头的网络边缘侧，融合网络、计算、存储、应用核心能力的分布式开放平台，就近提供边缘智能服务，满足行业数字化在敏捷联接、实时业务、数据优化、应用智能、安全与隐私保护等方面的关键需求。

- 人工智能（Artificial Intelligence, 缩略语:AI） :: 研究开发用于模拟、延伸和扩展人类智能的理论、方法、技术及应用系统的一门新技术科学。

- 工业大数据 :: 在工业领域中围绕典型智能制造模式，从客户需求到销售、订单、计划、研发、设计、工艺、制造、采购、供应、库存、发货和交付、售后服务、运维、报废或回收再制造等整个产品全生命周期各环节，所产生的各类数据及相关技术和应用的总称。

- 虚拟现实 :: 借助计算机系统及传感器技术生成一种模拟环境，通过交互式的三维动态视景和实体行为仿真，使用户沉浸到该环境中。

- 增强现实 :: 通过将三维内容投射到某介质上，呈现真实的人、场景与虚拟物体结合效果，与虚拟现实最大的不同是其中多了现实世界的东西，现实与虚拟融合。

- 混合现实（Mixed Reality, 缩略语：MR） :: 混合现实技术（MR）是虚拟现实技术的进一步发展，该技术通过在虚拟环境中引入现实场景信息，在虚拟世界、现实世界和用户之间搭起一个交互反馈的信息回路，以增强用户体验的真实感。

- 区块链（Blockchain） :: 分布式数据储存、点对点传输、共识机制、加密算法等计算机技术的新型应用模式。

- OPC 统一架构（OPC Unified Architecture） :: OPC 基金会（OPC Foundation）创建的新技术，更加安全、可靠、中立（与供应商无关），为制造现场到生产计划或企业资源计划（ERP）系统传输原始数据和预处理信息。
